# sampling parameter
training:
  train_share: 0.9 # the rest is validation set
  subscription_id_suffix: 'A' # '' for all users
  chosen_date: '2019-10-01' # '' for most recent data
  stages:
    - filter_users
    - take_last_date

fe:
  train_share: 0.9 # the rest is validation set
  subscription_id_suffix: 'AA' # '' for all users
  chosen_date: '2019-10-01' # '' for most recent data
  stages:
    - filter_users
    - take_last_date

scoring:
  subscription_id_suffix: '' # '' for all users
  chosen_date: '' # '' for most recent data
  stages:
    - take_last_date

scoring_experiment:
  subscription_id_suffix: '' # '' for all users
  chosen_date: '' # '' for most recent data
  stages:
    - take_last_date

report:
  subscription_id_suffix: '' # '' for all users
  chosen_date: '' # '' for most recent data
  stages:
    - take_last_date

# Column to be included in every table
key_columns:
  - key_date
  - subscription_identifier

# Columns indicating micro and macrosegments
segment_columns:
  - ard_macrosegment
  - churn_macrosegment

must_have_features:
  # macrosegments
  - subscriber_tenure
  - sum_rev_arpu_total_revenue_monthly_last_month
  # microsegment
  - volatility
  - sum_usg_incoming_number_calls_sum_weekly_last_twelve_week
  - sum_usg_total_data_volume_sum_weekly_last_twelve_week
  - sum_rev_arpu_total_revenue_monthly_last_month
  - sum_rev_arpu_total_revenue_monthly_last_three_month
  - sum_rev_arpu_total_gprs_net_revenue_monthly_last_three_month
  - sum_payments_top_ups_daily_last_ninety_day
  - avg_payments_top_up_volume_daily_last_ninety_day
  - sum_payments_top_ups_daily_last_ninety_day
  - last_activity_date
  - sum_usg_incoming_number_calls_sum_weekly_last_twelve_week
  - sum_usg_total_data_volume_sum_weekly_last_twelve_week
  - sum_usg_outgoing_data_volume_daily_last_thirty_day
  - sum_usg_outgoing_total_call_duration_daily_last_thirty_day
  - sum_usg_data_weekend_usage_sum_weekly_last_four_week
  - sum_usg_data_weekday_usage_sum_weekly_last_four_week
  - sum_usg_outgoing_weekend_number_calls_sum_weekly_last_four_week
  - sum_usg_outgoing_weekday_number_calls_sum_weekly_last_four_week
  # enforce usage of call center feature
  - sum_touchpoints_number_of_calls_on_cc_sum_weekly_last_two_week

# volatility
volatility_length: 5

# pai parameters
pai_runs_path: '/dbfs/mnt/customer360-blob-data/cvm/pai01/runs'
pai_artifacts_path: '/dbfs/mnt/customer360-blob-data/cvm/pai01/artifacts'
pai_experiment_name: 'force_call_center'

# subscription id replacement dictionary path
id_replace_dict_path: '/mnt/customer360-blob-output/C360/PROFILE/l1_features/l1_customer_profile_union_daily_feature/'
