# sampling parameter
training:
  train_share: 0.9 # the rest is validation set
  subscription_id_hash_suffix:  # '' for all users
  - '00'
  - '01'
  - '02'
  - '03'
  - '04'
  - '05'
  chosen_date: '2020-08-01' # '' for most recent data
  stages:
    - filter_users
    - take_last_date

fe:
  train_share: 0.9 # the rest is validation set
  subscription_id_hash_suffix: 'aa' # '' for all users
  chosen_date: '2020-08-01' # '' for most recent data
  stages:
    - filter_users
    - take_last_date

validation:
  train_share: 0.9 # the rest is validation set
  subscription_id_hash_suffix: '' # '' for all users
  chosen_date: '2020-11-01' # '' for most recent data
  stages:
    - filter_users
    - take_last_date

scoring:
  subscription_id_hash_suffix: '' # '' for all users
  chosen_date: '' # '' for most recent data
  stages:
    - take_last_date

scoring_all:
  subscription_id_hash_suffix: '' # '' for all users
  chosen_date: '' # '' for most recent data
  stages:
    - take_last_date

scoring_experiment:
  subscription_id_hash_suffix: '' # '' for all users
  chosen_date: '2020-01-08' # '' for most recent data
  stages:
    - take_last_date

report:
  subscription_id_hash_suffix: '' # '' for all users
  chosen_date: '' # '' for most recent data
  stages:
    - take_last_date

# Column to be included in every table
key_columns:
  - key_date
  - subscription_identifier

# Columns indicating micro and macrosegments
segment_columns:
  - ard_macrosegment
  - churn_macrosegment

must_have_features:
  # macrosegments
  - subscriber_tenure
  - sum_rev_arpu_total_revenue_monthly_last_month
  # microsegment
  - volatility
  - sum_usg_incoming_number_calls_sum_weekly_last_twelve_week
  - sum_usg_total_data_volume_sum_weekly_last_twelve_week
  - sum_rev_arpu_total_revenue_monthly_last_month
  - sum_rev_arpu_total_revenue_monthly_last_three_month
  - sum_rev_arpu_total_gprs_net_revenue_monthly_last_three_month
  - sum_payments_top_ups_daily_last_ninety_day
  - avg_payments_top_up_volume_daily_last_ninety_day
  - sum_payments_top_ups_daily_last_ninety_day
  - last_activity_date
  - sum_usg_incoming_number_calls_sum_weekly_last_twelve_week
  - sum_usg_total_data_volume_sum_weekly_last_twelve_week
  - sum_usg_outgoing_data_volume_daily_last_thirty_day
  - sum_usg_outgoing_total_call_duration_daily_last_thirty_day
  - sum_usg_data_weekend_usage_sum_weekly_last_four_week
  - sum_usg_data_weekday_usage_sum_weekly_last_four_week
  - sum_usg_outgoing_weekend_number_calls_sum_weekly_last_four_week
  - sum_usg_outgoing_weekday_number_calls_sum_weekly_last_four_week
  # enforce usage of call center feature
  - sum_touchpoints_number_of_calls_on_cc_sum_weekly_last_two_week

# Column to be removed from model
ิblacklist_columns:
  - national_id_card
  - access_method_num
  - register_date

# volatility
volatility_length: 5

# how often should the scoring microsegments be updated
microsegments_update_cadence: 30

# if "yes" then macrosegments and microsegments are forced to be recalculated
# use when changing the microsegments or macrosegments
force_micro_macrosegments_recalculation: 'yes'

# pai parameters
pai_runs_path: '/dbfs/mnt/customer360-blob-data/cvm/pai01/runs'
pai_artifacts_path: '/dbfs/mnt/customer360-blob-data/cvm/pai01/artifacts'
pai_experiment_name: 'internal_churn_02'

# path used to create temp copies for refreshments
refresh_temp_path: '/dbfs/mnt/customer360-blob-data/C360/CVM/l5_cvm_temp/'

# path used for checkpoints
checkpoint_path: '/dbfs/mnt/customer360-blob-data/C360/CVM/l5_cvm_checkpoint/'

# dbfs logs path
logs_path:
  output_path_template: '/dbfs/mnt/customer360-blob-data/cvm/logs/logs_{}'
  output_path_date_format: '%Y%m%d%H%M%S'

# weights used to create customer id
customer_id_weights:
  zipcode: 6
  age: 4
  handset_imei: 9
  home_weekday_location_id: 9
  home_weekend_location_id: 8.5
  work_location_id: 8.5
  strong_national_id_card: 30
  weak_national_id_card: 4

# threshold for customer connections
customer_id_thresholds:
  customer_id_high_certainty: 25
  customer_id_medium_certainty: 10
  customer_id_low_certainty: 1

# select only TG to generate user list
user_list_target_only: 'yes' # 'yes' select only target groups

# parameter to export table to path
export_table:
  scoring_all: # export propensity scores for all eligible customer
    output_path_template: '/mnt/customer360-blob-output/CVM_OUTPUT/cvm_prepaid_churn_ard_score/CVM_propensity_scores_{}.txt'
    output_path_date_format: '%Y%m%d%H%M%S'