# sampling parameter
training:
  train_share: 0.9 # the rest is validation set
  sampling: # what users to pick, what date to pick
    subscription_id_suffix: 'A' # '' for all users
    chosen_date: '2020-02-01' # '' for most recent data
    stages:
      - filter_users

scoring:
  sampling:
    subscription_id_suffix: '' # '' for all users
    chosen_date: '' # '' for most recent data
    stages:
      - take_last_date
      - filter_users

# Column to be included in every table
key_columns:
  - key_date
  - subscription_identifier

# Columns indicating micro and macrosegments
segment_columns:
  - ard_macrosegment
  - churn_macrosegment

# List of macrosegments
macrosegments:
  ard:
    - low_arpu_high_tenure
    - high_arpu_low_tenure
    - high_arpu_high_tenure
    - low_arpu_low_tenure
  churn:
    - zero_arpu
    - positive_arpu

must_have_features:
  # macrosegments
  - subscriber_tenure
  - sum_rev_arpu_total_revenue_monthly_last_month
  # microsegment
  - volatility
  - sum_usg_incoming_number_calls_sum_weekly_last_twelve_week
  - sum_usg_total_data_volume_sum_weekly_last_twelve_week
  - sum_rev_arpu_total_revenue_monthly_last_month
  - sum_rev_arpu_total_revenue_monthly_last_three_month
  - sum_rev_arpu_total_gprs_net_revenue_monthly_last_three_month
  - sum_payments_top_ups_daily_last_ninety_day
  - avg_payments_top_up_volume_daily_last_ninety_day
  - sum_payments_top_ups_daily_last_ninety_day
  - max_usg_last_action_date_daily_last_ninety_day
  - sum_usg_incoming_number_calls_sum_weekly_last_twelve_week
  - sum_usg_total_data_volume_sum_weekly_last_twelve_week
  - sum_usg_outgoing_data_volume_daily_last_thirty_day
  - sum_usg_outgoing_total_call_duration_daily_last_thirty_day
  - sum_usg_data_weekend_usage_sum_weekly_last_four_week
  - sum_usg_data_weekday_usage_sum_weekly_last_four_week
  - sum_usg_outgoing_weekend_number_calls_sum_weekly_last_four_week
  - sum_usg_outgoing_weekday_number_calls_sum_weekly_last_four_week

# volatility
volatility_length: 5

# pai parameters
pai_runs_path: '/dbfs/mnt/customer360-blob-data/cvm/pai01/runs'
pai_artifacts_path: '/dbfs/mnt/customer360-blob-data/cvm/pai01/artifacts'
pai_experiment_name: 'easter_model'
