# sampling parameters
chosen_date: '2019-10-01'
scoring_date: '2020-03-21'
subscription_id_suffix_dev: 'AB'
subscription_id_suffix_sample: 'A'
subscription_id_suffix_scoring_dev: 'AB'
subscription_id_suffix_scoring_sample: 'A'
training_sampling:
  - filter_users
scoring_sampling:
  - take_last_date
  - filter_users

# List of targets
targets:
  ard:
    dilution1:
      colname: 'dilution1'
      unit_of_analysis: 'month'
      length: 1
      drop: 0.1
      target_type: 'class'
    dilution2:
      colname: 'dilution2'
      unit_of_analysis: 'month'
      length: 3
      drop: 0.2
      target_type: 'class'
  churn:
    churn5:
      colname: 'churn5'
      inactivity_length: 5
      blindspot: 14
      target_type: 'class'
    churn15:
      colname: 'churn15'
      inactivity_length: 15
      blindspot: 14
      target_type: 'class'
    churn30:
      colname: 'churn30'
      inactivity_length: 30
      blindspot: 14
      target_type: 'class'
    churn45:
      colname: 'churn45'
      inactivity_length: 45
      blindspot: 14
      target_type: 'class'
    churn60:
      colname: 'churn60'
      inactivity_length: 60
      blindspot: 14
      target_type: 'class'

# Train / test split table parameters
l5_cvm_one_day_train_test:
  train_share: 0.9

# Column to be included in every table
key_columns:
  - key_date
  - subscription_identifier

# Columns indicating micro and macrosegments
segment_columns:
  - ard_macrosegment
  - churn_macrosegment

# List of macrosegments
macrosegments:
  ard:
    - low_arpu_high_tenure
    - high_arpu_low_tenure
    - high_arpu_high_tenure
    - low_arpu_low_tenure
  churn:
    - zero_arpu
    - positive_arpu

must_have_features:
  - subscriber_tenure
  - sum_rev_arpu_total_revenue_monthly_last_month

# volatility
volatility_length: 5

