# sampling parameters
training:
  sampling:
    subscription_id_suffix: 'A' # '' for all users
    chosen_date: '2019-10-01' # '' for most recent data
    stages:
      - filter_users

scoring:
  sampling:
    subscription_id_suffix: '' # '' for all users
    chosen_date: '2020-03-21' # '' for most recent data
    stages:
      - take_last_date
      - filter_users

# Train / test split table parameters
l5_cvm_one_day_train_test:
  train_share: 0.9

# Column to be included in every table
key_columns:
  - key_date
  - subscription_identifier

# Columns indicating micro and macrosegments
segment_columns:
  - ard_macrosegment
  - churn_macrosegment

# List of macrosegments
macrosegments:
  ard:
    - low_arpu_high_tenure
    - high_arpu_low_tenure
    - high_arpu_high_tenure
    - low_arpu_low_tenure
  churn:
    - zero_arpu
    - positive_arpu

must_have_features:
  - subscriber_tenure
  - sum_rev_arpu_total_revenue_monthly_last_month
  - volatility

# volatility
volatility_length: 5

# pai parameters
pai_runs_path: '/dbfs/mnt/customer360-blob-data/cvm/pai01/runs'
pai_artifacts_path: '/dbfs/mnt/customer360-blob-data/cvm/pai01/artifacts'
pai_experiment_name: 'reduced_cols_model'
