# Minimum date for l5_cvm_users_table creation
l5_cvm_users_table:
  min_date: "2019-08-31"

# Reve drop targets
l5_cvm_ard_monthly_targets:
  targets:
    dilution1:
      colname: 'dilution1'
      unit_of_analysis: 'month'
      length: 1
      drop: 0.1
    dilution2:
      colname: 'dilution2'
      unit_of_analysis: 'month'
      length: 3
      drop: 0.2

# Train / test split table parameters
l5_cvm_monthly_train_test:
  train_share: 0.8
