# Minimum date for l5_cvm_users_table creation
l5_cvm_one_day_users_table:
  date_chosen: "2019-11-01"

# List of targets
targets:
  ard:
    dilution1:
      colname: 'dilution1'
      unit_of_analysis: 'month'
      length: 1
      drop: 0.1
    dilution2:
      colname: 'dilution2'
      unit_of_analysis: 'month'
      length: 3
      drop: 0.2
  churn:
#    churn5:
#      colname: 'churn5'
#      inactivity_length: 5
#      blindspot: 14
#    churn15:
#      colname: 'churn15'
#      inactivity_length: 15
#      blindspot: 14
    churn30:
      colname: 'churn30'
      inactivity_length: 30
      blindspot: 14
    churn45:
      colname: 'churn45'
      inactivity_length: 45
      blindspot: 14
#    churn60:
#      colname: 'churn60'
#      inactivity_length: 60
#      blindspot: 14

# Train / test split table parameters
l5_cvm_one_day_train_test:
  train_share: 0.9
