l4_sales_number_and_volume_on_top_transaction_weekly: "l4_sales_number_and_volume_on_top_transaction_weekly"
l4_sales_number_and_volume_main_transaction_weekly: "l4_sales_number_and_volume_main_transaction_weekly"
