dq_consistency_path_prefix: data/DQ/dq_consistency_benchmark_dataset/

threshold_lookback_corresponding_dates: 120

incremental_mode: "off" # on = incremental mode activated / off = incremental mode deactivated

num_of_calls_outlier:  &num_of_calls_outlier
  outlier_formula: "sum(case when {col} < 0 or {col} > 500 then 1 else 0 end)"

features_for_dq:
  l4_touchpoints_to_call_center_features:
    - feature: sum_touchpoints_number_of_calls_on_cc_sum_weekly_last_week
      <<: *num_of_calls_outlier
    - feature: sum_touchpoints_number_of_calls_on_cc_sum_weekly_last_two_week
      <<: *num_of_calls_outlier
    - feature: sum_touchpoints_number_of_calls_on_cc_sum_weekly_last_four_week
      <<: *num_of_calls_outlier
    - feature: sum_touchpoints_number_of_calls_on_cc_sum_weekly_last_twelve_week

  l3_customer_profile_include_1mo_non_active:
    - feature: "*"
    - feature: "age"
      calculate_most_freq_value: True
