repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
        files: src/customer360/pipelines/cvm
    -   id: end-of-file-fixer
        files: src/customer360/pipelines/cvm
    -   id: check-yaml
        files: src/customer360/pipelines/cvm
    -   id: check-added-large-files
        files: src/customer360/pipelines/cvm
    -   id: check-merge-conflict
        files: src/customer360/pipelines/cvm
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
      files: src/customer360/pipelines/cvm
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      files: src/customer360/pipelines/cvm
