repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
        files: src/[cvm/nba]
    -   id: end-of-file-fixer
        files: src/[cvm/nba]
    -   id: check-yaml
        files: conf/base/CVM
    -   id: check-added-large-files
        files: src/[cvm/nba]
    -   id: check-merge-conflict
        files: src/[cvm/nba]
-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
    - id: isort
      files: src/[cvm/nba]
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
      files: src/[cvm/nba]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      files: src/[cvm/nba]
