# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from pipeline.py and the example nodes in
# `src/pipelines/`

cloud_on_prim_path_conversion:
  -
      search_pattern: "/PROFILE/"
      source_path_on_cloud_prefix: "/mnt/customer360-blob-data/C360/PROFILE"
      source_path_on_prem_prefix: "hdfs://10.237.82.9:8020/C360/CUSTOMER_PROFILE"
      target_path_on_cloud_prefix: "/mnt/customer360-blob-output/C360/PROFILE"
      target_path_on_prem_prefix: "/projects/prod/c360/data/CUSTOMER_PROFILE"

  -
      search_pattern: "/CAMPAIGN/"
      source_path_on_cloud_prefix: "/mnt/customer360-blob-data/C360/CAMPAIGN"
      source_path_on_prem_prefix: "hdfs://10.237.82.9:8020/C360/CAMPAIGN"
      target_path_on_cloud_prefix: "/mnt/customer360-blob-output/C360/CAMPAIGN"
      target_path_on_prem_prefix: "/projects/prod/c360/data/CAMPAIGN"

  -
      search_pattern: "/REVENUE/"
      source_path_on_cloud_prefix: "/mnt/customer360-blob-data/C360/REVENUE"
      source_path_on_prem_prefix: "hdfs://10.237.82.9:8020/C360/FINANCE_REVENUE"
      target_path_on_cloud_prefix: "/mnt/customer360-blob-output/C360/REVENUE"
      target_path_on_prem_prefix: "/projects/prod/c360/data/FINANCE_REVENUE"

  -
      search_pattern: "/TOUCHPOINTS/"
      source_path_on_cloud_prefix: "/mnt/customer360-blob-data/C360/TOUCHPOINTS"
      source_path_on_prem_prefix: "hdfs://10.237.82.9:8020/C360/TOUCHPOINTS"
      target_path_on_cloud_prefix: "/mnt/customer360-blob-output/C360/TOUCHPOINTS"
      target_path_on_prem_prefix: "/projects/prod/c360/data/TOUCHPOINTS"

  -
      search_pattern: "/USAGE/"
      source_path_on_cloud_prefix: "/mnt/customer360-blob-data/C360/USAGE"
      source_path_on_prem_prefix: "hdfs://10.237.82.9:8020/C360/USAGE"
      target_path_on_cloud_prefix: "/mnt/customer360-blob-output/C360/USAGE"
      target_path_on_prem_prefix: "/projects/prod/c360/data/USAGE"

  -
      search_pattern: "/DIGITAL/"
      source_path_on_cloud_prefix: "/mnt/customer360-blob-data/C360/ONLINE"
      source_path_on_prem_prefix: "hdfs://10.237.82.9:8020/C360/DIGITAL"
      target_path_on_cloud_prefix: "/mnt/customer360-blob-output/C360/DIGITAL"
      target_path_on_prem_prefix: "/projects/prod/c360/data/DIGITAL"

  -
      search_pattern: "/DEVICE/"
      source_path_on_cloud_prefix: "/mnt/customer360-blob-data/C360/DEVICE"
      source_path_on_prem_prefix: "hdfs://10.237.82.9:8020/C360/DEVICE"
      target_path_on_cloud_prefix: "/mnt/customer360-blob-output/C360/DEVICE"
      target_path_on_prem_prefix: "/projects/prod/c360/data/DEVICE"

  -
      search_pattern: "/STREAM/"
      source_path_on_cloud_prefix: "/mnt/customer360-blob-data/C360/STREAM"
      source_path_on_prem_prefix: "hdfs://10.237.82.9:8020/C360/STREAMING"
      target_path_on_cloud_prefix: "/mnt/customer360-blob-output/C360/STREAM"
      target_path_on_prem_prefix: "/projects/prod/c360/data/STREAMING"

  -
      search_pattern: "/NETWORK/"
      source_path_on_cloud_prefix: "/mnt/customer360-blob-data/C360/NETWORK"
      source_path_on_prem_prefix: "hdfs://10.237.82.9:8020/C360/NETWORK"
      target_path_on_cloud_prefix: "/mnt/customer360-blob-output/C360/NETWORK"
      target_path_on_prem_prefix: "/projects/prod/c360/data/NETWORK"

  -
      search_pattern: "/PRODUCT/"
      source_path_on_cloud_prefix: "/mnt/customer360-blob-data/C360/PRODUCT"
      source_path_on_prem_prefix: "hdfs://10.237.82.9:8020/C360/PRODUCT_AND_SERVICES"
      target_path_on_cloud_prefix: "/mnt/customer360-blob-output/C360/PRODUCT"
      target_path_on_prem_prefix: "/projects/prod/c360/data/PRODUCT_AND_SERVICES"

  -
      search_pattern: "/LOYALTY/"
      source_path_on_cloud_prefix: "/mnt/customer360-blob-data/C360/LOYALTY"
      source_path_on_prem_prefix: "hdfs://10.237.82.9:8020/C360/LOYALTY"
      target_path_on_cloud_prefix: "/mnt/customer360-blob-output/C360/LOYALTY"
      target_path_on_prem_prefix: "/projects/prod/c360/data/LOYALTY"


metadata_path:
    on_cloud: '/mnt/customer360-blob-output/C360/metadata_table'
    on_premise: '/projects/prod/c360/data/metadata/metadata_table'

