# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from pipeline.py and the example nodes in
# `src/pipelines/`

args:
  - PROFILE:
      search_pattern: "PROFILE"
      source_path_cloud_prefix: "/mnt/customer360-blob-data/C360/PROFILE"
      source_path_on_prem_prefix: "hdfs://10.237.82.9:8020/C360/CUSTOMER_PROFILE"
      target_path_cloud_prefix: "/mnt/customer360-blob-output/C360/PROFILE"
      target_path_on_prem_prefix: "/projects/prod/c360/data/CUSTOMER_PROFILE"
  - GEOLOCATION:
      search_pattern: "GEO"
      source_path_cloud_prefix: "/mnt/customer360-blob-data/C360/GEO"
      source_path_on_prem_prefix: "hdfs://10.237.82.9:8020/C360/GEOLOCATION"
      target_path_cloud_prefix: "/mnt/customer360-blob-output/C360/GEO"
      target_path_on_prem_prefix: "/projects/prod/c360/data/GEOLOCATION"
