# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from pipeline.py and the example nodes in
# `src/pipelines/`

int_l1_streaming_content_type_features_tbl: "int_l1_streaming_content_type_features"
int_l1_streaming_tv_channel_features_tbl: "int_l1_streaming_tv_channel_features"
int_l1_streaming_video_service_feature_tbl: "int_l1_streaming_video_service_feature"
int_l1_streaming_music_service_feature_tbl: "int_l1_streaming_music_service_feature"
int_l1_streaming_esport_service_feature_tbl: "int_l1_streaming_esport_service_feature"
l1_streaming_fav_content_group_by_volume_tbl: "l1_streaming_fav_content_group_by_volume"
l1_streaming_fav_content_group_by_duration_tbl: "l1_streaming_fav_content_group_by_duration"
l1_streaming_fav_tv_channel_by_volume_tbl: "l1_streaming_fav_tv_channel_by_volume"
l1_streaming_fav_tv_channel_by_duration_tbl: "l1_streaming_fav_tv_channel_by_duration"
l1_streaming_fav_video_service_by_download_feature_tbl: "l1_streaming_fav_video_service_by_download_feature"
l1_streaming_2nd_fav_video_service_by_download_feature_tbl: "l1_streaming_2nd_fav_video_service_by_download_feature"
l1_streaming_fav_music_service_by_download_feature_tbl: "l1_streaming_fav_music_service_by_download_feature"
l1_streaming_2nd_fav_music_service_by_download_feature_tbl: "l1_streaming_2nd_fav_music_service_by_download_feature"
l1_streaming_fav_esport_service_by_download_feature_tbl: "l1_streaming_fav_esport_service_by_download_feature"
l1_streaming_2nd_fav_esport_service_by_download_feature_tbl: "l1_streaming_2nd_fav_esport_service_by_download_feature"
l1_streaming_visit_count_and_download_traffic_feature_tbl: "l1_streaming_visit_count_and_download_traffic_feature"
l1_streaming_session_duration_feature_tbl: "l1_streaming_session_duration_feature"
int_l0_streaming_vimmi_table_tbl: "int_l0_streaming_vimmi_table"
l1_streaming_fav_tv_show_by_episode_watched_tbl: "l1_streaming_fav_tv_show_by_episode_watched"
