# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from pipeline.py and the example nodes in
# `src/pipelines/`

int_l2_streaming_content_type_features_tbl: "int_l2_streaming_content_type_features"
int_l2_streaming_tv_channel_features_tbl: "int_l2_streaming_tv_channel_features"
int_l2_streaming_video_service_feature_tbl: "int_l2_streaming_video_service_feature"
int_l2_streaming_music_service_feature_tbl: "int_l2_streaming_music_service_feature"
int_l2_streaming_esport_service_feature_tbl: "int_l2_streaming_esport_service_feature"
int_l2_streaming_sum_per_day_tbl: "int_l2_streaming_sum_per_day"
l2_streaming_fav_content_group_by_volume_tbl: "l2_streaming_fav_content_group_by_volume"
l2_streaming_fav_content_group_by_duration_tbl: "l2_streaming_fav_content_group_by_duration"
l2_streaming_fav_tv_channel_by_volume_tbl: "l2_streaming_fav_tv_channel_by_volume"
l2_streaming_fav_tv_channel_by_duration_tbl: "l2_streaming_fav_tv_channel_by_duration"
l2_streaming_fav_tv_show_by_episode_watched_tbl: "l2_streaming_fav_tv_show_by_episode_watched"
l2_streaming_fav_video_service_by_download_feature_tbl: "l2_streaming_fav_video_service_by_download_feature"
l2_streaming_2nd_fav_video_service_by_download_feature_tbl: "l2_streaming_2nd_fav_video_service_by_download_feature"
l2_streaming_fav_video_service_by_visit_count_feature_tbl: "l2_streaming_fav_video_service_by_visit_count_feature"
l2_streaming_fav_music_service_by_download_feature_tbl: "l2_streaming_fav_music_service_by_download_feature"
l2_streaming_2nd_fav_music_service_by_download_feature_tbl: "l2_streaming_2nd_fav_music_service_by_download_feature"
l2_streaming_fav_music_service_by_visit_count_feature_tbl: "l2_streaming_fav_music_service_by_visit_count_feature"
l2_streaming_fav_esport_service_by_download_feature_tbl: "l2_streaming_fav_esport_service_by_download_feature"
l2_streaming_2nd_fav_esport_service_by_download_feature_tbl: "l2_streaming_2nd_fav_esport_service_by_download_feature"
l2_streaming_fav_esport_service_by_visit_count_feature_tbl: "l2_streaming_fav_esport_service_by_visit_count_feature"
l2_streaming_visit_count_and_download_traffic_feature_tbl: "l2_streaming_visit_count_and_download_traffic_feature"
l2_streaming_fav_youtube_video_streaming_day_of_week_feature_tbl: "l2_streaming_fav_youtube_video_streaming_day_of_week_feature"
l2_streaming_session_duration_feature_tbl: "l2_streaming_session_duration_feature"

streaming_app:
  - "youtube_video"
  - "facebook_video"
  - "linetv_video"
  - "ais_play_video"
  - "netflix_video"
  - "viu_video"
  - "iflix_video"
  - "spotify_music"
  - "joox_music"
  - "twitch_esport"
  - "bigo_esport"
  - "mixer_esport"
  - "steamtv_esport"
