# Configuration to specify all the things needed to run the data quality pipeline
# Params:
# `features_for_dq`:
#    key: dataset name
#    value: List of dict containing 2 keys:
#     - `feature`: name of the feature to be processed.
#                 If you specify asterisk (*) e.g. feature: "*", it will process all "numeric" columns.
#                 You can still put outlier formula per individual column (see example below).
#                 You can also process non numeric column by specifying the feature after the * (see example below).
#
#     - (optional) `outlier_formula`: SQL logic to count the outlier value.
#                                     You can use {col} as placeholder for current column name (see the example below)
#
#    Example (this will process all columns in `l4_touchpoints_to_call_center_features`
#    and run the outlier formula the specified column):
#
#    l4_touchpoints_to_call_center_features:
#      - feature: '*'
#      - feature: sum_touchpoints_number_of_calls_on_cc_sum_weekly_last_week
#        outlier_formula: "sum(case when {col} < 0 or {col} > 500 then 1 else 0 end)"
#      - feature: subscription_identifier  <-- this will include subscription_identifier in the process

sample_size: 100000

percentiles:
  accuracy: 100
  percentile_list:
    - 0.1
    - 0.25  # do not removed. For outlier calculation
    - 0.5
    - 0.75  # do not removed. For outlier calculation
    - 0.9

dq_consistency_path_prefix: DQ/dq_consistency_benchmark_dataset

benchmark_start_date: "2020-01-01"
benchmark_end_date: "2020-11-30"

threshold_lookback_corresponding_dates: 120


incremental_mode: "off" # on = incremental mode activated / off = incremental mode deactivated


features_for_dq:
  l1_revenue_prepaid_pru_f_usage_multi_daily:
    - feature: 'access_method_num'
    - feature: 'start_of_week'
    - feature: 'start_of_month'
    - feature: 'subscription_identifier'
    - feature: 'rev_arpu_total_net_rev'
    - feature: 'rev_arpu_net_tariff_rev_reward'
    - feature: 'rev_arpu_net_tariff_rev_exc_reward'
    - feature: 'rev_arpu_share_of_exc_reward_over_total_rev'
    - feature: 'rev_arpu_share_of_revenue_reward_over_total_rev'
    - feature: 'rev_arpu_diff_in_exc_reward_rev_reward'
    - feature: 'rev_arpu_data_number_of_on_top_pkg'
    - feature: 'rev_arpu_data_rev'
    - feature: 'rev_arpu_data_rev_by_on_top_pkg'
    - feature: 'rev_arpu_data_rev_by_ppu'
    - feature: 'rev_arpu_data_rev_4g'
    - feature: 'rev_arpu_share_data_rev_4g'
    - feature: 'rev_arpu_data_rev_by_on_top_4g'
    - feature: 'rev_arpu_share_data_rev_by_pkg_4g'
    - feature: 'rev_arpu_data_rev_by_ppu_4g'
    - feature: 'rev_arpu_share_data_rev_by_ppu_4g'
    - feature: 'rev_arpu_data_rev_2g_3g'
    - feature: 'rev_arpu_share_data_rev_2g_3g'
    - feature: 'rev_arpu_data_rev_by_on_top_pkg_2g_3g'
    - feature: 'rev_arpu_share_data_rev_by_on_top_pkg_2g_3g'
    - feature: 'rev_arpu_data_rev_by_ppu_2g_3g'
    - feature: 'rev_arpu_share_data_rev_by_ppu_2g_3g'
    - feature: 'rev_arpu_data_rev_by_per_unit'
    - feature: 'rev_arpu_data_rev_per_unit_2g_3g'
    - feature: 'rev_arpu_data_rev_per_unit_4g'
    - feature: 'rev_arpu_diff_rev_by_on_top_pkg_ppu'
    - feature: 'rev_arpu_diff_rev_by_on_top_pkg_ppu_4g'
    - feature: 'rev_arpu_diff_rev_by_on_top_pkg_ppu_2g_3g'
    - feature: 'rev_arpu_diff_rev_2g_3g_vs_4g'
    - feature: 'rev_arpu_diff_rev_per_unit_2g_3g_vs_4g'
    - feature: 'rev_arpu_voice'
    - feature: 'rev_arpu_voice_intra_ppu'
    - feature: 'rev_arpu_share_voice_intra'
    - feature: 'rev_arpu_voice_non_intra_ppu'
    - feature: 'rev_arpu_share_voice_non_intra'
    - feature: 'rev_arpu_voice_per_call'
    - feature: 'rev_arpu_voice_intra_per_call'
    - feature: 'rev_arpu_voice_non_intra_per_call'
    - feature: 'rev_arpu_voice_per_minute'
    - feature: 'rev_arpu_voice_intra_per_minute'
    - feature: 'rev_arpu_voice_non_intra_per_minute'
    - feature: 'rev_arpu_diff_voice_intra_non_intra'
    - feature: 'rev_arpu_diff_voice_intra_non_intra_per_min'
    - feature: 'rev_arpu_diff_voice_intra_non_intra_per_call'
    - feature: 'rev_arpu_days_0_rev'
    - feature: 'rev_arpu_days_data_0_rev'
    - feature: 'rev_arpu_days_data_on_top_pkg_0_rev'
    - feature: 'rev_arpu_days_data_ppu_0_rev'
    - feature: 'rev_arpu_days_4g_data_0_rev'
    - feature: 'rev_arpu_days_2g_3g_data_0_rev'
    - feature: 'rev_arpu_days_4g_data_on_top_pkg_0_rev'
    - feature: 'rev_arpu_days_2g_3g_data_on_top_pkg_0_rev'
    - feature: 'rev_arpu_days_4g_data_ppu_0_rev'
    - feature: 'rev_arpu_days_2g_3g_data_ppu_0_rev'
    - feature: 'rev_arpu_days_voice_0_rev'
    - feature: 'rev_arpu_days_voice_intra_0_rev'
    - feature: 'rev_arpu_days_voice_non_intra_0_rev'
    - feature: 'rev_arpu_days_voice_per_call_0_rev'
    - feature: 'rev_arpu_days_voice_intra_per_call_0_rev'
    - feature: 'rev_arpu_days_voice_non_intra_per_call_0_rev'
    - feature: 'rev_arpu_days_voice_per_min_0_rev'
    - feature: 'rev_arpu_days_voice_intra_per_min_0_rev'
    - feature: 'rev_arpu_days_voice_non_intra_per_min_0_rev'
    - feature: 'rev_arpu_data_last_date_on_top_pkg'
    - feature: 'event_partition_date'
  l1_billing_and_payments_daily_topup_and_volume:
    - feature: 'start_of_month'
    - feature: 'start_of_week'
    - feature: 'access_method_num'
    - feature: 'register_date'
    - feature: 'subscription_identifier'
    - feature: 'payments_top_ups'
    - feature: 'payments_top_up_volume'
    - feature: 'event_partition_date'
  l1_devices_summary_customer_handset_daily:
    - feature: 'access_method_num'
    - feature: 'start_of_week'
    - feature: 'date_id'
    - feature: 'register_date'
    - feature: 'network_type'
    - feature: 'mobile_status'
    - feature: 'handset_usage_type'
    - feature: 'handset_imei'
    - feature: 'handset_change_time'
    - feature: 'handset_first_use_time'
    - feature: 'handset_last_use_time'
    - feature: 'handset_last_use_at_province'
    - feature: 'handset_brand_code'
    - feature: 'handset_model_code'
    - feature: 'handset_brand_name'
    - feature: 'handset_model_name'
    - feature: 'handset_type'
    - feature: 'handset_support_3g_2100_yn'
    - feature: 'handset_use_imsi'
    - feature: 'handset_wds_flag'
    - feature: 'handset_channel'
    - feature: 'ota_change_imsi'
    - feature: 'ota_oma_wap'
    - feature: 'ready_3g_internet_setting'
    - feature: 'dual_sim'
    - feature: 'apn_group'
    - feature: 'mobile_no_in_same_imei'
    - feature: 'sim_card_serial_num'
    - feature: 'sim_card_version'
    - feature: 'sim_card_pin_capacity'
    - feature: 'lte_frequency'
    - feature: 'hs_support_lte_1800'
    - feature: 'execution_id'
    - feature: 'account_status'
    - feature: 'dualsim_imei_wds'
    - feature: 'dualsim_imei_slot_flag'
    - feature: 'dualsim_imei_use_flag'
    - feature: 'handset_technology'
    - feature: 'ais_handset_technology'
    - feature: 'imei_3g4g_yn'
    - feature: 'imei_4g_yn'
    - feature: 'ma_name'
    - feature: 'no_of_mobile_ais'
    - feature: 'no_of_same_model'
    - feature: 'dual_user_yn'
    - feature: 'partition_date'
    - feature: 'subscription_identifier'
    - feature: 'event_partition_date'
  l3_revenue_prepaid_ru_f_sum_revenue_by_service_monthly:
    - feature: 'subscription_identifier'
    - feature: 'month_id'
    - feature: 'rev_arpu_total_revenue'
    - feature: 'rev_arpu_total_gprs_net_revenue'
    - feature: 'rev_arpu_total_vas_net_revenue'
    - feature: 'rev_arpu_total_sms_net_revenue'
    - feature: 'rev_arpu_total_others_net_revenue'
    - feature: 'rev_arpu_total_voice_net_revenue'
    - feature: 'rev_arpu_total_mms_net_revenue'
    - feature: 'rev_arpu_total_ir_net_revenue'
    - feature: 'rev_arpu_total_idd_net_revenue'
    - feature: 'rev_arpu_total_voice_net_tariff_rev_mth'
    - feature: 'rev_arpu_total_gprs_net_tariff_rev_mth'
    - feature: 'rev_arpu_total_sms_net_tariff_rev_mth'
    - feature: 'rev_arpu_total_mms_net_tariff_rev_mth'
    - feature: 'rev_arpu_total_others_net_tariff_rev_mth'
    - feature: 'rev_arpu_total_voice_net_tariff_rev_ppu'
    - feature: 'rev_arpu_total_gprs_net_tariff_rev_ppu'
    - feature: 'rev_arpu_total_sms_net_tariff_rev_ppu'
    - feature: 'rev_arpu_total_mms_net_tariff_rev_ppu'
    - feature: 'rev_arpu_total_others_net_tariff_rev_ppu'
    - feature: 'rev_arpu_total_ir_net_tariff_rev_ppu'
    - feature: 'rev_arpu_total_idd_net_tariff_rev_ppu'
    - feature: 'start_of_month'