# Configuration to specify all the things needed to run the data quality pipeline
# Params:
# `features_for_dq`:
#    key: dataset name
#    value: List of dict containing 2 keys:
#     - `feature`: name of the feature to be processed.
#                 If you specify asterisk (*) e.g. feature: "*", it will process all "numeric" columns.
#                 You can still put outlier formula per individual column (see example below).
#                 You can also process non numeric column by specifying the feature after the * (see example below).
#
#     - (optional) `outlier_formula`: SQL logic to count the outlier value.
#                                     You can use {col} as placeholder for current column name (see the example below)
#
#    Example (this will process all columns in `l4_touchpoints_to_call_center_features`
#    and run the outlier formula the specified column):
#
#    l4_touchpoints_to_call_center_features:
#      - feature: '*'
#      - feature: sum_touchpoints_number_of_calls_on_cc_sum_weekly_last_week
#        outlier_formula: "sum(case when {col} < 0 or {col} > 500 then 1 else 0 end)"
#      - feature: subscription_identifier  <-- this will include subscription_identifier in the process

sample_size: 100000

percentiles:
  accuracy: 100
  percentile_list:
    - 0.1
    - 0.25  # do not removed. For outlier calculation
    - 0.5
    - 0.75  # do not removed. For outlier calculation
    - 0.9

dq_consistency_path_prefix: DQ/dq_consistency_benchmark_dataset

benchmark_start_date: "2020-01-01"
benchmark_end_date: "2020-07-30"

threshold_lookback_corresponding_dates: 120


incremental_mode: "off" # on = incremental mode activated / off = incremental mode deactivated


features_for_dq:
  l1_usage_postpaid_prepaid_daily:
    - feature: 'access_method_num'
    - feature: 'start_of_week'
    - feature: 'start_of_month'
    - feature: 'subscription_identifier'
    - feature: 'access_method_number'
    - feature: 'date_id'
    - feature: 'usg_data_friday_afternoon_usage'
    - feature: 'usg_data_friday_evening_usage'
    - feature: 'usg_data_friday_morning_usage'
    - feature: 'usg_data_friday_night_usage'
    - feature: 'usg_data_friday_usage'
    - feature: 'usg_data_last_action_date'
    - feature: 'usg_data_monday_afternoon_usage'
    - feature: 'usg_data_monday_evening_usage'
    - feature: 'usg_data_monday_morning_usage'
    - feature: 'usg_data_monday_night_usage'
    - feature: 'usg_data_monday_usage'
    - feature: 'usg_data_saturday_afternoon_usage'
    - feature: 'usg_data_saturday_evening_usage'
    - feature: 'usg_data_saturday_morning_usage'
    - feature: 'usg_data_saturday_night_usage'
    - feature: 'usg_data_saturday_usage'
    - feature: 'usg_data_sunday_afternoon_usage'
    - feature: 'usg_data_sunday_evening_usage'
    - feature: 'usg_data_sunday_morning_usage'
    - feature: 'usg_data_sunday_night_usage'
    - feature: 'usg_data_sunday_usage'
    - feature: 'usg_data_thursday_afternoon_usage'
    - feature: 'usg_data_thursday_evening_usage'
    - feature: 'usg_data_thursday_morning_usage'
    - feature: 'usg_data_thursday_night_usage'
    - feature: 'usg_data_thursday_usage'
    - feature: 'usg_data_tuesday_afternoon_usage'
    - feature: 'usg_data_tuesday_evening_usage'
    - feature: 'usg_data_tuesday_morning_usage'
    - feature: 'usg_data_tuesday_night_usage'
    - feature: 'usg_data_tuesday_usage'
    - feature: 'usg_data_wednesday_afternoon_usage'
    - feature: 'usg_data_wednesday_evening_usage'
    - feature: 'usg_data_wednesday_morning_usage'
    - feature: 'usg_data_wednesday_night_usage'
    - feature: 'usg_data_wednesday_usage'
    - feature: 'usg_data_weekday_usage'
    - feature: 'usg_data_weekend_usage'
    - feature: 'usg_incoming_afternoon_number_sms'
    - feature: 'usg_incoming_afternoon_time_call'
    - feature: 'usg_incoming_afternoon_time_call_duration'
    - feature: 'usg_incoming_ais_local_calls_duration'
    - feature: 'usg_incoming_ais_local_number_calls'
    - feature: 'usg_incoming_data_volume'
    - feature: 'usg_incoming_data_volume_2G_3G'
    - feature: 'usg_incoming_data_volume_4G'
    - feature: 'usg_incoming_dtac_call_duration'
    - feature: 'usg_incoming_dtac_number_calls'
    - feature: 'usg_incoming_dtac_number_sms'
    - feature: 'usg_incoming_evening_number_sms'
    - feature: 'usg_incoming_evening_time_call'
    - feature: 'usg_incoming_evening_time_call_duration'
    - feature: 'usg_incoming_favourite_numbers_call_duration'
    - feature: 'usg_incoming_favourite_numbers_local_call_duration'
    - feature: 'usg_incoming_favourite_numbers_local_number_of_calls'
    - feature: 'usg_incoming_favourite_numbers_local_sms_number'
    - feature: 'usg_incoming_favourite_numbers_number_of_calls'
    - feature: 'usg_incoming_favourite_numbers_roaming_call_duration'
    - feature: 'usg_incoming_favourite_numbers_roaming_number_of_calls'
    - feature: 'usg_incoming_favourite_numbers_roaming_sms_number'
    - feature: 'usg_incoming_favourite_numbers_sms_number'
    - feature: 'usg_incoming_friday_afternoon_voice_usage'
    - feature: 'usg_incoming_friday_evening_voice_usage'
    - feature: 'usg_incoming_friday_morning_voice_usage'
    - feature: 'usg_incoming_friday_night_voice_usage'
    - feature: 'usg_incoming_friday_voice_usage'
    - feature: 'usg_incoming_last_call_date'
    - feature: 'usg_incoming_last_sms_date'
    - feature: 'usg_incoming_local_ais_sms'
    - feature: 'usg_incoming_local_call_duration'
    - feature: 'usg_incoming_local_data_volume'
    - feature: 'usg_incoming_local_data_volume_2G_3G'
    - feature: 'usg_incoming_local_data_volume_4G'
    - feature: 'usg_incoming_local_number_calls'
    - feature: 'usg_incoming_local_sms'
    - feature: 'usg_incoming_monday_afternoon_voice_usage'
    - feature: 'usg_incoming_monday_evening_voice_usage'
    - feature: 'usg_incoming_monday_morning_voice_usage'
    - feature: 'usg_incoming_monday_night_voice_usage'
    - feature: 'usg_incoming_monday_voice_usage'
    - feature: 'usg_incoming_morning_time_call'
    - feature: 'usg_incoming_morning_time_call_duration'
    - feature: 'usg_incoming_morning_time_number_sms'
    - feature: 'usg_incoming_night_time_call'
    - feature: 'usg_incoming_night_time_call_duration'
    - feature: 'usg_incoming_night_time_number_sms'
    - feature: 'usg_incoming_number_calls'
    - feature: 'usg_incoming_number_calls_over_30_mins'
    - feature: 'usg_incoming_number_calls_upto_10_mins'
    - feature: 'usg_incoming_number_calls_upto_15_mins'
    - feature: 'usg_incoming_number_calls_upto_20_mins'
    - feature: 'usg_incoming_number_calls_upto_30_mins'
    - feature: 'usg_incoming_number_calls_upto_5_mins'
    - feature: 'usg_incoming_offnet_local_calls_duration'
    - feature: 'usg_incoming_offnet_local_number_calls'
    - feature: 'usg_incoming_relative_favourite_numbers_call_duration'
    - feature: 'usg_incoming_relative_favourite_numbers_local_call_duration'
    - feature: 'usg_incoming_relative_favourite_numbers_local_number_of_calls'
    - feature: 'usg_incoming_relative_favourite_numbers_local_sms_number'
    - feature: 'usg_incoming_relative_favourite_numbers_number_of_calls'
    - feature: 'usg_incoming_relative_favourite_numbers_roaming_sms_number'
    - feature: 'usg_incoming_relative_favourite_numbers_sms_number'
    - feature: 'usg_incoming_relative_numbers_roaming_call_duration'
    - feature: 'usg_incoming_relative_numbers_roaming_number_of_calls'
    - feature: 'usg_incoming_roaming_call_duration'
    - feature: 'usg_incoming_roaming_data_volume'
    - feature: 'usg_incoming_roaming_data_volume_2G_3G'
    - feature: 'usg_incoming_roaming_data_volume_4G'
    - feature: 'usg_incoming_roaming_last_sms_date'
    - feature: 'usg_incoming_roaming_number_calls'
    - feature: 'usg_incoming_roaming_total_sms'
    - feature: 'usg_incoming_saturday_afternoon_voice_usage'
    - feature: 'usg_incoming_saturday_evening_voice_usage'
    - feature: 'usg_incoming_saturday_morning_voice_usage'
    - feature: 'usg_incoming_saturday_night_voice_usage'
    - feature: 'usg_incoming_saturday_voice_usage'
    - feature: 'usg_incoming_sunday_afternoon_voice_usage'
    - feature: 'usg_incoming_sunday_evening_voice_usage'
    - feature: 'usg_incoming_sunday_morning_voice_usage'
    - feature: 'usg_incoming_sunday_night_voice_usage'
    - feature: 'usg_incoming_sunday_voice_usage'
    - feature: 'usg_incoming_thursday_afternoon_voice_usage'
    - feature: 'usg_incoming_thursday_evening_voice_usage'
    - feature: 'usg_incoming_thursday_morning_voice_usage'
    - feature: 'usg_incoming_thursday_night_voice_usage'
    - feature: 'usg_incoming_thursday_voice_usage'
    - feature: 'usg_incoming_total_call_duration'
    - feature: 'usg_incoming_total_sms'
    - feature: 'usg_incoming_true_call_duration'
    - feature: 'usg_incoming_true_number_calls'
    - feature: 'usg_incoming_true_number_sms'
    - feature: 'usg_incoming_tuesday_afternoon_voice_usage'
    - feature: 'usg_incoming_tuesday_evening_voice_usage'
    - feature: 'usg_incoming_tuesday_morning_voice_usage'
    - feature: 'usg_incoming_tuesday_night_voice_usage'
    - feature: 'usg_incoming_tuesday_voice_usage'
    - feature: 'usg_incoming_wednesday_afternoon_voice_usage'
    - feature: 'usg_incoming_wednesday_evening_voice_usage'
    - feature: 'usg_incoming_wednesday_morning_voice_usage'
    - feature: 'usg_incoming_wednesday_night_voice_usage'
    - feature: 'usg_incoming_wednesday_voice_usage'
    - feature: 'usg_incoming_weekday_calls_duration'
    - feature: 'usg_incoming_weekday_number_calls'
    - feature: 'usg_incoming_weekday_number_sms'
    - feature: 'usg_incoming_weekend_calls_duration'
    - feature: 'usg_incoming_weekend_number_calls'
    - feature: 'usg_incoming_weekend_number_sms'
    - feature: 'usg_last_action_date'
    - feature: 'usg_last_call_date'
    - feature: 'usg_last_sms_date'
    - feature: 'usg_outgoing_afternoon_number_calls'
    - feature: 'usg_outgoing_afternoon_number_sms'
    - feature: 'usg_outgoing_afternoon_time_call_duration'
    - feature: 'usg_outgoing_ais_local_calls_duration'
    - feature: 'usg_outgoing_ais_local_number_calls'
    - feature: 'usg_outgoing_data_volume'
    - feature: 'usg_outgoing_data_volume_2G_3G'
    - feature: 'usg_outgoing_data_volume_4G'
    - feature: 'usg_outgoing_dtac_call_duration'
    - feature: 'usg_outgoing_dtac_number_calls'
    - feature: 'usg_outgoing_dtac_number_sms'
    - feature: 'usg_outgoing_evening_number_calls'
    - feature: 'usg_outgoing_evening_number_sms'
    - feature: 'usg_outgoing_evening_time_call_duration'
    - feature: 'usg_outgoing_favourite_numbers_call_duration'
    - feature: 'usg_outgoing_favourite_numbers_local_call_duration'
    - feature: 'usg_outgoing_favourite_numbers_local_number_of_calls'
    - feature: 'usg_outgoing_favourite_numbers_local_sms_number'
    - feature: 'usg_outgoing_favourite_numbers_number_of_calls'
    - feature: 'usg_outgoing_favourite_numbers_roaming_call_duration'
    - feature: 'usg_outgoing_favourite_numbers_roaming_number_of_calls'
    - feature: 'usg_outgoing_favourite_numbers_roaming_sms_number'
    - feature: 'usg_outgoing_favourite_numbers_sms_number'
    - feature: 'usg_outgoing_friday_afternoon_voice_usage'
    - feature: 'usg_outgoing_friday_evening_voice_usage'
    - feature: 'usg_outgoing_friday_morning_voice_usage'
    - feature: 'usg_outgoing_friday_night_voice_usage'
    - feature: 'usg_outgoing_friday_voice_usage'
    - feature: 'usg_outgoing_last_call_date'
    - feature: 'usg_outgoing_last_sms_date'
    - feature: 'usg_outgoing_local_ais_sms'
    - feature: 'usg_outgoing_local_call_duration'
    - feature: 'usg_outgoing_local_data_volume'
    - feature: 'usg_outgoing_local_data_volume_2G_3G'
    - feature: 'usg_outgoing_local_data_volume_4G'
    - feature: 'usg_outgoing_local_number_calls'
    - feature: 'usg_outgoing_local_sms'
    - feature: 'usg_outgoing_monday_afternoon_voice_usage'
    - feature: 'usg_outgoing_monday_evening_voice_usage'
    - feature: 'usg_outgoing_monday_morning_voice_usage'
    - feature: 'usg_outgoing_monday_night_voice_usage'
    - feature: 'usg_outgoing_monday_voice_usage'
    - feature: 'usg_outgoing_morning_time_calls_duration'
    - feature: 'usg_outgoing_morning_time_number_calls'
    - feature: 'usg_outgoing_morning_time_number_sms'
    - feature: 'usg_outgoing_night_time_calls_duration'
    - feature: 'usg_outgoing_night_time_number_calls'
    - feature: 'usg_outgoing_night_time_number_sms'
    - feature: 'usg_outgoing_number_calls'
    - feature: 'usg_outgoing_number_calls_over_30_mins'
    - feature: 'usg_outgoing_number_calls_upto_10_mins'
    - feature: 'usg_outgoing_number_calls_upto_15_mins'
    - feature: 'usg_outgoing_number_calls_upto_20_mins'
    - feature: 'usg_outgoing_number_calls_upto_30_mins'
    - feature: 'usg_outgoing_number_calls_upto_5_mins'
    - feature: 'usg_outgoing_offnet_local_calls_duration'
    - feature: 'usg_outgoing_offnet_local_number_calls'
    - feature: 'usg_outgoing_relative_favourite_numbers_call_duration'
    - feature: 'usg_outgoing_relative_favourite_numbers_local_call_duration'
    - feature: 'usg_outgoing_relative_favourite_numbers_local_number_of_calls'
    - feature: 'usg_outgoing_relative_favourite_numbers_local_sms_number'
    - feature: 'usg_outgoing_relative_favourite_numbers_number_of_calls'
    - feature: 'usg_outgoing_relative_favourite_numbers_roaming_sms_number'
    - feature: 'usg_outgoing_relative_favourite_numbers_sms_number'
    - feature: 'usg_outgoing_relative_numbers_roaming_call_duration'
    - feature: 'usg_outgoing_relative_numbers_roaming_number_of_calls'
    - feature: 'usg_outgoing_roaming_call_duration'
    - feature: 'usg_outgoing_roaming_data_volume'
    - feature: 'usg_outgoing_roaming_data_volume_2G_3G'
    - feature: 'usg_outgoing_roaming_data_volume_4G'
    - feature: 'usg_outgoing_roaming_last_sms_date'
    - feature: 'usg_outgoing_roaming_number_calls'
    - feature: 'usg_outgoing_roaming_total_sms'
    - feature: 'usg_outgoing_saturday_afternoon_voice_usage'
    - feature: 'usg_outgoing_saturday_evening_voice_usage'
    - feature: 'usg_outgoing_saturday_morning_voice_usage'
    - feature: 'usg_outgoing_saturday_night_voice_usage'
    - feature: 'usg_outgoing_saturday_voice_usage'
    - feature: 'usg_outgoing_sunday_afternoon_voice_usage'
    - feature: 'usg_outgoing_sunday_evening_voice_usage'
    - feature: 'usg_outgoing_sunday_morning_voice_usage'
    - feature: 'usg_outgoing_sunday_night_voice_usage'
    - feature: 'usg_outgoing_sunday_voice_usage'
    - feature: 'usg_outgoing_thursday_afternoon_voice_usage'
    - feature: 'usg_outgoing_thursday_evening_voice_usage'
    - feature: 'usg_outgoing_thursday_morning_voice_usage'
    - feature: 'usg_outgoing_thursday_night_voice_usage'
    - feature: 'usg_outgoing_thursday_voice_usage'
    - feature: 'usg_outgoing_total_call_duration'
    - feature: 'usg_outgoing_total_sms'
    - feature: 'usg_outgoing_true_call_duration'
    - feature: 'usg_outgoing_true_number_calls'
    - feature: 'usg_outgoing_true_number_sms'
    - feature: 'usg_outgoing_tuesday_afternoon_voice_usage'
    - feature: 'usg_outgoing_tuesday_evening_voice_usage'
    - feature: 'usg_outgoing_tuesday_morning_voice_usage'
    - feature: 'usg_outgoing_tuesday_night_voice_usage'
    - feature: 'usg_outgoing_tuesday_voice_usage'
    - feature: 'usg_outgoing_wednesday_afternoon_voice_usage'
    - feature: 'usg_outgoing_wednesday_evening_voice_usage'
    - feature: 'usg_outgoing_wednesday_morning_voice_usage'
    - feature: 'usg_outgoing_wednesday_night_voice_usage'
    - feature: 'usg_outgoing_wednesday_voice_usage'
    - feature: 'usg_outgoing_weekday_calls_duration'
    - feature: 'usg_outgoing_weekday_number_calls'
    - feature: 'usg_outgoing_weekday_number_sms'
    - feature: 'usg_outgoing_weekend_calls_duration'
    - feature: 'usg_outgoing_weekend_number_calls'
    - feature: 'usg_outgoing_weekend_number_sms'
    - feature: 'usg_total_data_last_action_date'
    - feature: 'usg_total_data_volume'
    - feature: 'usg_vas_last_action_dt'
    - feature: 'usg_vas_total_number_of_call'
