sample_size: 100000

percentiles:
  accuracy: 80
  percentile_list:
    - 0.1
    - 0.9



num_of_calls_outlier:  &num_of_calls_outlier
  outlier_formula: "sum(case when {col} < 0 or {col} > 500 then 1 else 0 end)"

features_for_dq:
#  l4_touchpoints_to_call_center_features:
#    - feature: sum_touchpoints_number_of_calls_on_cc_sum_weekly_last_week
#      <<: *num_of_calls_outlier
#    - feature: sum_touchpoints_number_of_calls_on_cc_sum_weekly_last_two_week
#      <<: *num_of_calls_outlier
#    - feature: sum_touchpoints_number_of_calls_on_cc_sum_weekly_last_four_week
#      <<: *num_of_calls_outlier
#    - feature: sum_touchpoints_number_of_calls_on_cc_sum_weekly_last_twelve_week
  l3_customer_profile_include_1mo_non_active:
#    - feature: subscription_status
    - feature: age
#    - feature: gender
    - feature: time_with_current_package
#    - feature: customer_segment
#    - feature: serenade_status
#    - feature: network_type
#    - feature: acquisition_channel
    - feature: subscriber_tenure
#    - feature: activation_region
#    - feature: current_package_name
#    - feature: current_package_id
#    - feature: company_type
#    - feature: cust_active_this_month
    - feature: norms_net_revenue
  l4_billing_rolling_window_topup_and_volume:
    - feature: sum_payments_top_ups_last_week
    - feature: sum_payments_top_ups_last_four_week
    - feature: sum_payments_top_ups_last_twelve_week
  l4_billing_rolling_window_rpu: #all features
    - feature: sum_payments_arpu_last_month
    - feature: sum_payments_arpu_last_three_month
    - feature: sum_payments_arpu_gprs_last_month
    - feature: sum_payments_arpu_gprs_last_three_month
    - feature: sum_payments_arpu_vas_last_month
    - feature: sum_payments_arpu_vas_last_three_month
    - feature: sum_payments_arpu_voice_last_month
    - feature: sum_payments_arpu_voice_last_three_month
#    - feature: avg_payments_arpu_last_month
#    - feature: avg_payments_arpu_last_three_month
#    - feature: avg_payments_arpu_gprs_last_month
#    - feature: avg_payments_arpu_gprs_last_three_month
#    - feature: avg_payments_arpu_vas_last_month
#    - feature: avg_payments_arpu_vas_last_three_month
#    - feature: avg_payments_arpu_voice_last_month
#    - feature: avg_payments_arpu_voice_last_three_month
    - feature: payments_one_month_over_three_month_dynamics_arpu
#  l4_billing_rolling_window_rpu_roaming:
#    - feature: sum_payments_arpu_roaming_weekly_last_week
#    - feature: sum_payments_arpu_roaming_weekly_last_twelve_week
#  l4_billing_rolling_window_before_top_up_balance:
#    - feature: sum_payments_before_top_up_balance_weekly_last_week
#    - feature: sum_payments_before_top_up_balance_weekly_last_four_week
#  l4_billing_rolling_window_top_up_channels:
#    - feature: sum_payments_top_ups_by_bank_atm_cdm_weekly_last_twelve_week
#    - feature: sum_payments_top_up_vol_by_bank_atm_cdm_weekly_last_twelve_week
#    - feature: sum_payments_top_ups_by_cash_card_weekly_last_twelve_week
#    - feature: sum_payments_top_up_vol_by_cash_card_weekly_last_twelve_week
#    - feature: sum_payments_top_ups_by_digital_online_self_service_weekly_last_twelve_week
#    - feature: sum_payments_top_up_vol_by_digital_online_self_service_weekly_last_twelve_week
#    - feature: sum_payments_top_ups_by_epin_slip_weekly_last_twelve_week
#    - feature: sum_payments_top_up_vol_by_epin_slip_weekly_last_twelve_week
#    - feature: sum_payments_top_ups_by_epos_weekly_last_twelve_week
#    - feature: sum_payments_top_up_vol_by_epos_weekly_last_twelve_week
#    - feature: sum_payments_top_ups_by_rom_weekly_last_twelve_week
#    - feature: sum_payments_top_up_vol_by_rom_weekly_last_twelve_week
#  l4_daily_feature_topup_and_volume:
#    - feature: sum_payments_top_ups_daily_last_seven_day
#    - feature: sum_payments_top_ups_daily_last_thirty_day
#    - feature: sum_payments_top_ups_daily_last_ninety_day
#  l4_campaign_postpaid_prepaid_features:
#    - feature: sum_campaign_overall_count_sum_weekly_last_week
#    - feature: sum_campaign_overall_count_sum_weekly_last_two_week
#    - feature: sum_campaign_overall_count_sum_weekly_last_four_week
#    - feature: sum_campaign_overall_count_sum_weekly_last_twelve_week
#    - feature: sum_campaign_total_by_call_center_sum_weekly_last_week
#    - feature: sum_campaign_total_by_call_center_sum_weekly_last_twelve_week
#    - feature: sum_campaign_total_eligible_by_call_center_sum_weekly_last_week
#    - feature: sum_campaign_total_eligible_by_call_center_sum_weekly_last_twelve_week
#    - feature: sum_campaign_total_success_by_call_center_sum_weekly_last_week
#    - feature: sum_campaign_total_success_by_call_center_sum_weekly_last_twelve_week
#    - feature: sum_campaign_total_by_sms_sum_weekly_last_week
#    - feature: sum_campaign_total_by_sms_sum_weekly_last_twelve_week
#    - feature: sum_campaign_total_eligible_by_sms_sum_weekly_last_week
#    - feature: sum_campaign_total_eligible_by_sms_sum_weekly_last_twelve_week
#    - feature: sum_campaign_total_success_by_sms_sum_weekly_last_week
#    - feature: sum_campaign_total_success_by_sms_sum_weekly_last_twelve_week
#    - feature: sum_campaign_total_upsell_xsell_by_sms_sum_weekly_last_week
#    - feature: sum_campaign_total_upsell_xsell_by_sms_sum_weekly_last_twelve_week
#    - feature: sum_campaign_total_upsell_xsell_eligible_by_sms_sum_weekly_last_week
#    - feature: sum_campaign_total_upsell_xsell_eligible_by_sms_sum_weekly_last_twelve_week
#    - feature: sum_campaign_total_upsell_xsell_success_by_sms_sum_weekly_last_week
#    - feature: sum_campaign_total_upsell_xsell_success_by_sms_sum_weekly_last_twelve_week
#    - feature: sum_campaign_total_others_by_sms_sum_weekly_last_week
#    - feature: sum_campaign_total_others_by_sms_sum_weekly_last_twelve_week
#    - feature: sum_campaign_total_others_eligible_by_sms_sum_weekly_last_week
#    - feature: sum_campaign_total_others_eligible_by_sms_sum_weekly_last_twelve_week
#    - feature: sum_campaign_total_others_success_by_sms_sum_weekly_last_week
#    - feature: sum_campaign_total_others_success_by_sms_sum_weekly_last_twelve_week
#    - feature: sum_campaign_total_retention_by_sms_sum_weekly_last_week
#    - feature: sum_campaign_total_retention_by_sms_sum_weekly_last_twelve_week
#    - feature: sum_campaign_total_retention_eligible_by_sms_sum_weekly_last_week
#    - feature: sum_campaign_total_retention_eligible_by_sms_sum_weekly_last_twelve_week
#    - feature: sum_campaign_total_retention_success_by_sms_sum_weekly_last_week
#    - feature: sum_campaign_total_retention_success_by_sms_sum_weekly_last_twelve_week
#    - feature: sum_campaign_total_upsell_xsell_by_myais_app_sum_weekly_last_week
#    - feature: sum_campaign_total_upsell_xsell_by_myais_app_sum_weekly_last_twelve_week
#  l4_device_summary_features:
#    - feature: sum_device_most_used_handset_apple_weekly_last_week
#    - feature: max_device_high_range_weekly_last_week
#    - feature: max_device_mid_range_weekly_last_week
#    - feature: max_device_low_range_weekly_last_week
#    - feature: max_device_smartphone_weekly_last_week
#    - feature: max_device_standardphone_weekly_last_week
#    - feature: max_device_legacyphone_weekly_last_week
#  l4_revenue_prepaid_ru_f_sum_revenue_by_service_monthly:
#    - feature: sum_rev_arpu_total_revenue_monthly_last_month
#    - feature: sum_rev_arpu_total_revenue_monthly_last_three_month
#    - feature: sum_rev_arpu_total_gprs_net_revenue_monthly_last_month
#    - feature: sum_rev_arpu_total_sms_net_revenue_monthly_last_month
#    - feature: sum_rev_arpu_total_others_net_revenue_monthly_last_month
#    - feature: sum_rev_arpu_total_voice_net_revenue_monthly_last_month
#    - feature: sum_rev_arpu_total_mms_net_revenue_monthly_last_month
#    - feature: sum_rev_arpu_total_ir_net_revenue_monthly_last_month
#    - feature: sum_rev_arpu_total_idd_net_revenue_monthly_last_month
#    - feature: sum_rev_arpu_total_voice_net_tariff_rev_mth_monthly_last_month
#    - feature: sum_rev_arpu_total_gprs_net_tariff_rev_mth_monthly_last_month
#    - feature: sum_rev_arpu_total_sms_net_tariff_rev_mth_monthly_last_month
#    - feature: sum_rev_arpu_total_mms_net_tariff_rev_mth_monthly_last_month
#    - feature: sum_rev_arpu_total_others_net_tariff_rev_mth_monthly_last_month
#    - feature: sum_rev_arpu_total_voice_net_tariff_rev_ppu_monthly_last_month
#    - feature: sum_rev_arpu_total_gprs_net_tariff_rev_ppu_monthly_last_month
#    - feature: sum_rev_arpu_total_sms_net_tariff_rev_ppu_monthly_last_month
#    - feature: sum_rev_arpu_total_mms_net_tariff_rev_ppu_monthly_last_month
#    - feature: sum_rev_arpu_total_others_net_tariff_rev_ppu_monthly_last_month
#    - feature: sum_rev_arpu_total_ir_net_tariff_rev_ppu_monthly_last_month
#    - feature: sum_rev_arpu_total_idd_net_tariff_rev_ppu_monthly_last_month
#  l4_streaming_visit_count_and_download_traffic_feature:
#    - feature: sum_download_kb_traffic_youtube_video_sum_weekly_last_twelve_week
#    - feature: sum_download_kb_traffic_facebook_video_sum_weekly_last_week
#    - feature: sum_download_kb_traffic_facebook_video_sum_weekly_last_twelve_week
#    - feature: sum_download_kb_traffic_linetv_video_sum_weekly_last_week
#    - feature: sum_download_kb_traffic_ais_play_video_sum_weekly_last_week
#    - feature: sum_download_kb_traffic_netflix_video_sum_weekly_last_week
#  l4_usage_prepaid_postpaid_daily_features:
#    - feature: sum_usg_incoming_total_call_duration_daily_last_ninety_day
#    - feature: sum_usg_incoming_total_call_duration_daily_last_seven_day
#    - feature: sum_usg_outgoing_data_volume_daily_last_fourteen_day
#    - feature: sum_usg_outgoing_data_volume_daily_last_ninety_day
#    - feature: sum_usg_outgoing_data_volume_daily_last_seven_day
#    - feature: sum_usg_outgoing_total_call_duration_daily_last_ninety_day
#    - feature: sum_usg_outgoing_total_call_duration_daily_last_seven_day
#    - feature: sum_usg_outgoing_total_sms_daily_last_ninety_day
#    - feature: sum_usg_outgoing_total_sms_daily_last_seven_day
#  l4_usage_postpaid_prepaid_weekly_features_sum:
#    - feature: sum_usg_incoming_data_volume_sum_weekly_last_week
#    - feature: sum_usg_incoming_data_volume_sum_weekly_last_four_week
#    - feature: sum_usg_incoming_data_volume_sum_weekly_last_twelve_week
#    - feature: sum_usg_incoming_data_volume_2G_3G_sum_weekly_last_four_week
#    - feature: sum_usg_incoming_data_volume_4G_sum_weekly_last_four_week
#    - feature: sum_usg_incoming_local_data_volume_sum_weekly_last_four_week
#    - feature: sum_usg_incoming_local_data_volume_2G_3G_sum_weekly_last_four_week
#    - feature: sum_usg_incoming_local_data_volume_4G_sum_weekly_last_four_week
#    - feature: sum_usg_incoming_roaming_data_volume_sum_weekly_last_twelve_week
#    - feature: sum_usg_outgoing_data_volume_sum_weekly_last_four_week
#    - feature: sum_usg_total_data_volume_sum_weekly_last_week
#    - feature: sum_usg_total_data_volume_sum_weekly_last_four_week
#    - feature: sum_usg_total_data_volume_sum_weekly_last_twelve_week
#    - feature: sum_usg_incoming_roaming_call_duration_sum_weekly_last_week
#    - feature: sum_usg_incoming_roaming_call_duration_sum_weekly_last_twelve_week
#    - feature: sum_usg_incoming_local_call_duration_sum_weekly_last_week
#    - feature: sum_usg_incoming_local_call_duration_sum_weekly_last_four_week
#    - feature: sum_usg_incoming_local_call_duration_sum_weekly_last_twelve_week
#    - feature: sum_usg_incoming_total_sms_sum_weekly_last_week
#    - feature: sum_usg_incoming_total_sms_sum_weekly_last_twelve_week
#    - feature: sum_usg_incoming_weekday_calls_duration_sum_weekly_last_four_week
#    - feature: sum_usg_incoming_weekday_number_calls_sum_weekly_last_four_week
#    - feature: sum_usg_incoming_weekend_calls_duration_sum_weekly_last_four_week
#    - feature: sum_usg_incoming_weekend_number_calls_sum_weekly_last_four_week
#    - feature: sum_usg_outgoing_total_call_duration_sum_weekly_last_week
#    - feature: sum_usg_outgoing_total_call_duration_sum_weekly_last_four_week
#    - feature: sum_usg_outgoing_total_call_duration_sum_weekly_last_twelve_week
#    - feature: sum_usg_outgoing_total_sms_sum_weekly_last_week
#    - feature: sum_usg_outgoing_total_sms_sum_weekly_last_four_week
#    - feature: sum_usg_outgoing_total_sms_sum_weekly_last_twelve_week

