# Configuration to specify all the things needed to run the data quality pipeline
# Params:
# `features_for_dq`:
#    key: dataset name
#    value: List of dict containing 2 keys:
#     - `feature`: name of the feature to be processed.
#                 If you specify asterisk (*) e.g. feature: "*", it will process all "numeric" columns.
#                 You can still put outlier formula per individual column (see example below).
#                 You can also process non numeric column by specifying the feature after the * (see example below).
#
#     - (optional) `outlier_formula`: SQL logic to count the outlier value.
#                                     You can use {col} as placeholder for current column name (see the example below)
#
#    Example (this will process all columns in `l4_touchpoints_to_call_center_features`
#    and run the outlier formula the specified column):
#
#    l4_touchpoints_to_call_center_features:
#      - feature: '*'
#      - feature: sum_touchpoints_number_of_calls_on_cc_sum_weekly_last_week
#        outlier_formula: "sum(case when {col} < 0 or {col} > 500 then 1 else 0 end)"
#      - feature: subscription_identifier  <-- this will include subscription_identifier in the process

sample_size: 100000

percentiles:
  accuracy: 90
  percentile_list:
    - 0.1
    - 0.25  # do not removed. For outlier calculation
    - 0.5
    - 0.75  # do not removed. For outlier calculation
    - 0.9

dq_consistency_path_prefix: DQ/dq_consistency_benchmark_dataset

benchmark_start_date: "2020-01-01"
benchmark_end_date: "2020-07-30"

threshold_lookback_corresponding_dates: 120


incremental_mode: "off" # on = incremental mode activated / off = incremental mode deactivated


features_for_dq:
#  l4_geo_area_from_ais_store:
#      - feature: '*'
#  l4_geo_area_from_competitor_store:
#      - feature: '*'
#  l4_geo_call_location_home_work_weekly:
#      - feature: '*'
#  l4_geo_cust_subseqently_distance:
#      - feature: '*'
#  l4_geo_distance_top_call:
#      - feature: '*'
#  l4_geo_from_number_of_used_most_frequent_weekdays:
#      - feature: '*'
#  l4_geo_from_number_of_used_most_frequent_weekend:
#      - feature: '*'
#  l4_geo_from_number_of_used_most_frequent_weekends:
#      - feature: '*'
#  l4_geo_home_weekday_city_citizens:
#      - feature: '*'
  l4_geo_home_work_location_id:
      - feature: '*'
#  l4_geo_last_ais_store_visit:
#      - feature: '*'
#  l4_geo_most_ais_store_visit:
#      - feature: '*'
#  l4_geo_number_most_frequent_top_five:
#      - feature: '*'
#  l4_geo_number_most_frequent_top_five_weekdays:
#      - feature: '*'
#  l4_geo_number_most_frequent_top_five_weekends:
#      - feature: '*'
#  l4_geo_number_of_base_station:
#      - feature: '*'
#  l4_geo_number_unique_cell_used:
#      - feature: '*'
#  l4_geo_range_from_most_visited:
#      - feature: '*'
#  l4_geo_store_close_to_home:
#      - feature: '*'
#  l4_geo_store_close_to_work:
#      - feature: '*'
#  l4_geo_time_spent_by_location:
#      - feature: '*'
#  l4_geo_top3_cells_on_voice_usage:
#      - feature: '*'
#  l4_geo_top_visit_exclude_homework:
#      - feature: '*'
#  l4_geo_total_distance_km:
#      - feature: '*'
#  l4_geo_use_traffic_home_work_weekly:
#      - feature: '*'
#  l4_geo_work_area_center_average:
#      - feature: '*'
#  l4_same_favourite_location_weekend_weekday_weekly:
#      - feature: '*'
#  l4_the_favourite_locations_daily:
#      - feature: '*'
#  l4_the_most_frequently_location_weekdays:
#      - feature: '*'
#  l4_the_most_frequently_location_weekdays_4g:
#      - feature: '*'
#  l4_the_most_frequently_location_weekends:
#      - feature: '*'
