# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from pipeline.py and the example nodes in
# `src/pipelines/`


l2_touchpoints_to_call_center_features_tbl: "l2_touchpoints_to_call_center_features"
l2_touchpoints_from_call_center_features_tbl: "l2_touchpoints_from_call_center_features"
l2_touchpoints_nim_work_features_tbl: "l2_touchpoints_nim_work_features"
l2_touchpoints_ivr_features_tbl: "l2_touchpoints_ivr_features"
exception_partition_list_for_l1_touchpoints_to_call_center_features_for_l2_touchpoints_to_call_center_features: ['2020-01-27']
exception_partition_list_for_l1_touchpoints_from_call_center_features_for_l2_touchpoints_from_call_center_features: ['2020-01-27']
exception_partition_list_for_l1_touchpoints_nim_work_features_for_l2_touchpoints_nim_work_features: ['2020-01-27']
exception_partition_list_for_l1_touchpoints_ivr_features: ['2020-01-27']
