exception_partition_list_for_l0_network_sdr_dyn_cea_cei_qoe_cell_usr_voice_1day: ['2019-12-30'] # Monday before 1-Jan-20
exception_partition_list_for_l0_network_sdr_dyn_cea_cei_qoe_cell_usr_web_1day: ['2020-01-20'] # Monday before 23-Jan-20
exception_partition_list_for_l0_network_sdr_dyn_cea_cei_dataqoe_usr_1day: ['2020-07-27'] # Monday before 1-Aug-20
exception_partition_list_for_l0_network_sdr_dyn_cea_cei_cei_usr_1day: ['2020-07-27'] # Monday before 1-Aug-20
exception_partition_list_for_l0_geo_mst_cell_masterplan_current: ['2020-02-03'] # Monday before 5-Feb-2020

# Unused:
# exception_partition_list_for_l0_usage_sum_data_location_daily: ['2019-10-28'] # Monday before 1-Nov-2019

# Already Monday:
# l0_network_sdr_dyn_cea_cei_qoe_cell_usr_fileaccess_1day
# l0_network_sdr_dyn_cea_cei_qoe_cell_usr_im_1day
# l0_network_sdr_dyn_cea_cei_qoe_cell_usr_stream_1day
# l0_network_sdr_dyn_cea_cei_qoe_cell_usr_voip_1day
# l0_network_sdr_dyn_cea_cei_qoe_cell_usr_volte_1day: []