#target_table_names_parameter
l1_network_voice_cei_tbl: "l1_network_voice_cei"
l1_network_data_cei_tbl: "l1_network_data_cei"
l1_network_failed_outgoing_call_attempt_and_call_drop_3g_tbl: "l1_network_failed_outgoing_call_attempt_and_call_drop_3g"
l1_network_failed_incoming_call_attempt_and_call_drop_4g_tbl: "l1_network_failed_incoming_call_attempt_and_call_drop_4g"
l1_network_start_delay_and_success_rate_features_tbl: "l1_network_start_delay_and_success_rate_features"