
nba_master_table_date_min: "2019-10-15"
nba_master_table_date_max: "2020-03-31"

nba_min_feature_days_lag: 5  # TODO validate lag

# Parameters for model training
nba_model_group_column_prioritized: campaign_child_code
nba_model_group_column_non_prioritized: campaign_category
nba_model_group_column: model_group

nba_acceptance_model_target_column: target_response
nba_arpu_30d_model_target_column: target_relative_arpu_increase_30d
nba_arpu_7d_model_target_column: target_relative_arpu_increase_7d

nba_model_min_obs_per_class_for_model: 500
nba_model_max_rows_per_group: 1000000
nba_model_train_sampling_ratio: 0.8

regression_clip_target_quantiles_arpu: [0.05, 0.95]

nba_model_model_params:
   n_jobs: 1
   num_leaves: 16
   learning_rate: 0.02
   n_estimators: 200
   min_gain_to_split: 0.0
   random_state: 123456
   importance_type: "gain"

nba_pai_runs_uri: # TODO PLEASE COMPLETE WITH DATABASE URI
nba_pai_artifacts_uri: "dbfs://mnt/customer360-blob-data/NBA/pai_20200511/"

# Columns to track in NBA, they will be added in the PAI run info
nba_extra_tag_columns_pai:
  - child_name
  - campaign_category
  - campaign_child_code
  - campaign_type
  - campaign_sub_type
  - campaign_type_contact_policy

nba_prioritized_campaigns_child_codes:
  - "1-46493338111"
  - "1-49214431681"
  - "1-84074046175"
  - "1-47725105277"
  - "1-86944567111"
  - "1-62402989247"
  - "1-84153709846"
  - "1-84434245594"
  - "1-43008448667"
  - "1-54446727889"
  - "1-85816673891"
  - "1-80630046101"
  - "1-73943893353"
  - "1-76784686507"
  - "1-87970101195"
  - "1-54451059058"
  - "1-80630046121"
  - "1-76784686510"
  - "1-79530935324"
  - "1-86264889941"
  - "1-54316752745"
  - "1-55160941796"
  - "1-86664206547"
  - "1-54316118231"
  - "1-54446718862"
  - "1-78484433450"
  - "1-54343861463"
  - "1-67886346104"
  - "1-66853885414"
  - "1-65968305071"
  - "1-83796369622"
  - "1-69825842871"
  - "1-88800672973"
  - "1-85643645630"
  - "1-87970101204"
  - "1-86545475121"
  - "1-77521335684"
  - "1-77516159323"
  - "1-85820246910"
  - "1-84228520290"
  - "1-77260196524"
  - "1-76784686504"
  - "1-87974176862"
  - "1-50837815153"
  - "1-86165195198"
  - "1-83596949214"
  - "1-69708668724"
  - "1-77874144084"
  - "1-70583718777"
  - "1-78276630870"
  - "1-80350934870"
  - "1-87978968684"
  - "1-39641959290"
  - "1-40106241231"
  - "1-77874144124"
  - "1-81950524770"
  - "1-88361782764"
  - "1-88361782744"
  - "1-72408085056"
  - "1-77260196484"
  - "1-85307823831"
  - "1-85307823899"
  - "1-85307823896"
  - "1-85307823893"
  - "1-85307823834"
  - "1-85307823837"
  - "1-69825842851"
  - "1-85412125341"
  - "1-85412125344"
  - "200309-199"
  - "1-62076734859"
  - "1-66302497134"
  - "1-70306418171"
  - "1-70306418174"
  - "1-77128674807"
  - "1-88800672570"
  - "1-88831706630"
  - "1-63491118223"
  - "1-89305064474"
  - "1-89327222350"
  - "1-90160950091"
  - "1-90160950094"
  - "1-90160950099"
  - "1-90160950202"
  - "200312-33"
  - "1-82216451704"
  - "200323-19"
  - "200224-45"
  - "1-90529876760"
  - "200324-25"
  - "1-90544608454"
  - "1-90544608446"
  - "1-90544608460"
  - "200309-201"



# Parameters for master table (model input)
nba_model_input_features:
  l5_nba_customer_profile:
    - subscription_status
    - age
    - gender
    - time_with_current_package
    - customer_segment
    - serenade_status
    - network_type
    - acquisition_channel
    - subscriber_tenure
    - activation_region
    - current_package_name
    - current_package_id
    - moc_cust_type
    - cust_active_this_month
    - norms_net_revenue
    - charge_type_numeric
    - network_type_numeric
    - customer_segment_numeric
    - subscription_status_numeric
    - cust_active_this_month_numeric
  l4_billing_rolling_window_topup_and_volume:
    - sum_payments_top_ups_last_week
    - sum_payments_top_ups_last_four_week
    - sum_payments_top_ups_last_twelve_week
  l4_billing_rolling_window_rpu:
    - sum_payments_arpu_last_month
    - sum_payments_arpu_last_three_month
    - sum_payments_arpu_gprs_last_month
    - sum_payments_arpu_gprs_last_three_month
    - sum_payments_arpu_vas_last_month
    - sum_payments_arpu_vas_last_three_month
    - sum_payments_arpu_voice_last_month
    - sum_payments_arpu_voice_last_three_month
    - payments_one_month_over_three_month_dynamics_arpu
  l4_billing_rolling_window_rpu_roaming:
    - sum_payments_arpu_roaming_weekly_last_week
    - sum_payments_arpu_roaming_weekly_last_twelve_week
  l4_billing_rolling_window_before_top_up_balance:
    - sum_payments_before_top_up_balance_weekly_last_week
    - sum_payments_before_top_up_balance_weekly_last_four_week
  l4_billing_rolling_window_top_up_channels:
    - sum_payments_top_ups_by_bank_atm_cdm_weekly_last_twelve_week
    - sum_payments_top_up_vol_by_bank_atm_cdm_weekly_last_twelve_week
    - sum_payments_top_ups_by_cash_card_weekly_last_twelve_week
    - sum_payments_top_up_vol_by_cash_card_weekly_last_twelve_week
    - sum_payments_top_ups_by_digital_online_self_service_weekly_last_twelve_week
    - sum_payments_top_up_vol_by_digital_online_self_service_weekly_last_twelve_week
    - sum_payments_top_ups_by_epin_slip_weekly_last_twelve_week
    - sum_payments_top_up_vol_by_epin_slip_weekly_last_twelve_week
    - sum_payments_top_ups_by_epos_weekly_last_twelve_week
    - sum_payments_top_up_vol_by_epos_weekly_last_twelve_week
    - sum_payments_top_ups_by_rom_weekly_last_twelve_week
    - sum_payments_top_up_vol_by_rom_weekly_last_twelve_week
  l4_daily_feature_topup_and_volume:
    - sum_payments_top_ups_daily_last_seven_day
    - sum_payments_top_ups_daily_last_thirty_day
    - sum_payments_top_ups_daily_last_ninety_day
  l4_campaign_postpaid_prepaid_features:
    - sum_campaign_overall_count_sum_weekly_last_week
    - sum_campaign_overall_count_sum_weekly_last_two_week
    - sum_campaign_overall_count_sum_weekly_last_four_week
    - sum_campaign_overall_count_sum_weekly_last_twelve_week
    - sum_campaign_total_by_call_center_sum_weekly_last_week
    - sum_campaign_total_by_call_center_sum_weekly_last_twelve_week
    - sum_campaign_total_eligible_by_call_center_sum_weekly_last_week
    - sum_campaign_total_eligible_by_call_center_sum_weekly_last_twelve_week
    - sum_campaign_total_success_by_call_center_sum_weekly_last_week
    - sum_campaign_total_success_by_call_center_sum_weekly_last_twelve_week
    - sum_campaign_total_by_sms_sum_weekly_last_week
    - sum_campaign_total_by_sms_sum_weekly_last_twelve_week
    - sum_campaign_total_eligible_by_sms_sum_weekly_last_week
    - sum_campaign_total_eligible_by_sms_sum_weekly_last_twelve_week
    - sum_campaign_total_success_by_sms_sum_weekly_last_week
    - sum_campaign_total_success_by_sms_sum_weekly_last_twelve_week
    - sum_campaign_total_upsell_xsell_by_sms_sum_weekly_last_week
    - sum_campaign_total_upsell_xsell_by_sms_sum_weekly_last_twelve_week
    - sum_campaign_total_upsell_xsell_eligible_by_sms_sum_weekly_last_week
    - sum_campaign_total_upsell_xsell_eligible_by_sms_sum_weekly_last_twelve_week
    - sum_campaign_total_upsell_xsell_success_by_sms_sum_weekly_last_week
    - sum_campaign_total_upsell_xsell_success_by_sms_sum_weekly_last_twelve_week
    - sum_campaign_total_others_by_sms_sum_weekly_last_week
    - sum_campaign_total_others_by_sms_sum_weekly_last_twelve_week
    - sum_campaign_total_others_eligible_by_sms_sum_weekly_last_week
    - sum_campaign_total_others_eligible_by_sms_sum_weekly_last_twelve_week
    - sum_campaign_total_others_success_by_sms_sum_weekly_last_week
    - sum_campaign_total_others_success_by_sms_sum_weekly_last_twelve_week
    - sum_campaign_total_retention_by_sms_sum_weekly_last_week
    - sum_campaign_total_retention_by_sms_sum_weekly_last_twelve_week
    - sum_campaign_total_retention_eligible_by_sms_sum_weekly_last_week
    - sum_campaign_total_retention_eligible_by_sms_sum_weekly_last_twelve_week
    - sum_campaign_total_retention_success_by_sms_sum_weekly_last_week
    - sum_campaign_total_retention_success_by_sms_sum_weekly_last_twelve_week
    - sum_campaign_total_upsell_xsell_by_myais_app_sum_weekly_last_week
    - sum_campaign_total_upsell_xsell_by_myais_app_sum_weekly_last_twelve_week
  l4_device_summary_features:
    - sum_device_most_used_handset_apple_weekly_last_week
    - max_device_high_range_weekly_last_week
    - max_device_mid_range_weekly_last_week
    - max_device_low_range_weekly_last_week
    - max_device_smartphone_weekly_last_week
    - max_device_standardphone_weekly_last_week
    - max_device_legacyphone_weekly_last_week
  l4_revenue_prepaid_ru_f_sum_revenue_by_service_monthly:
    - sum_rev_arpu_total_revenue_monthly_last_month
    - sum_rev_arpu_total_revenue_monthly_last_three_month
    - sum_rev_arpu_total_gprs_net_revenue_monthly_last_month
    - sum_rev_arpu_total_sms_net_revenue_monthly_last_month
    - sum_rev_arpu_total_others_net_revenue_monthly_last_month
    - sum_rev_arpu_total_voice_net_revenue_monthly_last_month
    - sum_rev_arpu_total_mms_net_revenue_monthly_last_month
    - sum_rev_arpu_total_ir_net_revenue_monthly_last_month
    - sum_rev_arpu_total_idd_net_revenue_monthly_last_month
    - sum_rev_arpu_total_voice_net_tariff_rev_mth_monthly_last_month
    - sum_rev_arpu_total_gprs_net_tariff_rev_mth_monthly_last_month
    - sum_rev_arpu_total_sms_net_tariff_rev_mth_monthly_last_month
    - sum_rev_arpu_total_mms_net_tariff_rev_mth_monthly_last_month
    - sum_rev_arpu_total_others_net_tariff_rev_mth_monthly_last_month
    - sum_rev_arpu_total_voice_net_tariff_rev_ppu_monthly_last_month
    - sum_rev_arpu_total_gprs_net_tariff_rev_ppu_monthly_last_month
    - sum_rev_arpu_total_sms_net_tariff_rev_ppu_monthly_last_month
    - sum_rev_arpu_total_mms_net_tariff_rev_ppu_monthly_last_month
    - sum_rev_arpu_total_others_net_tariff_rev_ppu_monthly_last_month
    - sum_rev_arpu_total_ir_net_tariff_rev_ppu_monthly_last_month
    - sum_rev_arpu_total_idd_net_tariff_rev_ppu_monthly_last_month
  l4_streaming_visit_count_and_download_traffic_feature:
    - sum_download_kb_traffic_youtube_video_sum_weekly_last_twelve_week
    - sum_download_kb_traffic_facebook_video_sum_weekly_last_week
    - sum_download_kb_traffic_facebook_video_sum_weekly_last_twelve_week
    - sum_download_kb_traffic_linetv_video_sum_weekly_last_week
    - sum_download_kb_traffic_ais_play_video_sum_weekly_last_week
    - sum_download_kb_traffic_netflix_video_sum_weekly_last_week
  l4_usage_prepaid_postpaid_daily_features:
    - sum_usg_incoming_total_call_duration_daily_last_ninety_day
    - sum_usg_incoming_total_call_duration_daily_last_seven_day
    - sum_usg_outgoing_data_volume_daily_last_fourteen_day
    - sum_usg_outgoing_data_volume_daily_last_ninety_day
    - sum_usg_outgoing_data_volume_daily_last_seven_day
    - sum_usg_outgoing_total_call_duration_daily_last_ninety_day
    - sum_usg_outgoing_total_call_duration_daily_last_seven_day
    - sum_usg_outgoing_total_sms_daily_last_ninety_day
    - sum_usg_outgoing_total_sms_daily_last_seven_day
  l4_usage_postpaid_prepaid_weekly_features_sum:
    - sum_usg_incoming_data_volume_sum_weekly_last_week
    - sum_usg_incoming_data_volume_sum_weekly_last_four_week
    - sum_usg_incoming_data_volume_sum_weekly_last_twelve_week
    - sum_usg_incoming_data_volume_2G_3G_sum_weekly_last_four_week
    - sum_usg_incoming_data_volume_4G_sum_weekly_last_four_week
    - sum_usg_incoming_local_data_volume_sum_weekly_last_four_week
    - sum_usg_incoming_local_data_volume_2G_3G_sum_weekly_last_four_week
    - sum_usg_incoming_local_data_volume_4G_sum_weekly_last_four_week
    - sum_usg_incoming_roaming_data_volume_sum_weekly_last_twelve_week
    - sum_usg_outgoing_data_volume_sum_weekly_last_four_week
    - sum_usg_total_data_volume_sum_weekly_last_week
    - sum_usg_total_data_volume_sum_weekly_last_four_week
    - sum_usg_total_data_volume_sum_weekly_last_twelve_week
    - sum_usg_incoming_roaming_call_duration_sum_weekly_last_week
    - sum_usg_incoming_roaming_call_duration_sum_weekly_last_twelve_week
    - sum_usg_incoming_local_call_duration_sum_weekly_last_week
    - sum_usg_incoming_local_call_duration_sum_weekly_last_four_week
    - sum_usg_incoming_local_call_duration_sum_weekly_last_twelve_week
    - sum_usg_incoming_total_sms_sum_weekly_last_week
    - sum_usg_incoming_total_sms_sum_weekly_last_twelve_week
    - sum_usg_incoming_weekday_calls_duration_sum_weekly_last_four_week
    - sum_usg_incoming_weekday_number_calls_sum_weekly_last_four_week
    - sum_usg_incoming_weekend_calls_duration_sum_weekly_last_four_week
    - sum_usg_incoming_weekend_number_calls_sum_weekly_last_four_week
    - sum_usg_outgoing_total_call_duration_sum_weekly_last_week
    - sum_usg_outgoing_total_call_duration_sum_weekly_last_four_week
    - sum_usg_outgoing_total_call_duration_sum_weekly_last_twelve_week
    - sum_usg_outgoing_total_sms_sum_weekly_last_week
    - sum_usg_outgoing_total_sms_sum_weekly_last_four_week
    - sum_usg_outgoing_total_sms_sum_weekly_last_twelve_week


nba_model_explanatory_features:
   - age
   - time_with_current_package
   - subscriber_tenure
   - charge_type_numeric
   - network_type_numeric
   - customer_segment_numeric
   - subscription_status_numeric
   - cust_active_this_month_numeric
   - norms_net_revenue
   - sum_payments_arpu_last_month
   - sum_payments_arpu_last_three_month
   - sum_payments_arpu_gprs_last_month
   - sum_payments_arpu_gprs_last_three_month
   - sum_payments_arpu_vas_last_month
   - sum_payments_arpu_vas_last_three_month
   - sum_payments_arpu_voice_last_month
   - sum_payments_arpu_voice_last_three_month
   - sum_payments_before_top_up_balance_weekly_last_week
   - sum_payments_before_top_up_balance_weekly_last_four_week
   - sum_payments_top_ups_by_bank_atm_cdm_weekly_last_twelve_week
   - sum_payments_top_up_vol_by_bank_atm_cdm_weekly_last_twelve_week
   - sum_payments_top_ups_by_cash_card_weekly_last_twelve_week
   - sum_payments_top_up_vol_by_cash_card_weekly_last_twelve_week
   - sum_payments_top_ups_by_digital_online_self_service_weekly_last_twelve_week
   - sum_payments_top_up_vol_by_digital_online_self_service_weekly_last_twelve_week
   - sum_payments_top_ups_by_epin_slip_weekly_last_twelve_week
   - sum_payments_top_up_vol_by_epin_slip_weekly_last_twelve_week
   - sum_payments_top_ups_by_epos_weekly_last_twelve_week
   - sum_payments_top_up_vol_by_epos_weekly_last_twelve_week
   - sum_payments_top_ups_by_rom_weekly_last_twelve_week
   - sum_payments_top_up_vol_by_rom_weekly_last_twelve_week
   - sum_payments_top_ups_daily_last_seven_day
   - sum_payments_top_ups_daily_last_thirty_day
   - sum_payments_top_ups_daily_last_ninety_day
   - sum_campaign_overall_count_sum_weekly_last_week
   - sum_campaign_overall_count_sum_weekly_last_four_week
   - sum_campaign_overall_count_sum_weekly_last_twelve_week
   - sum_campaign_total_by_sms_sum_weekly_last_week
   - sum_campaign_total_by_sms_sum_weekly_last_twelve_week
   - sum_campaign_total_others_by_sms_sum_weekly_last_week
   - max_device_high_range_weekly_last_week
   - max_device_low_range_weekly_last_week
   - sum_rev_arpu_total_revenue_monthly_last_month
   - sum_rev_arpu_total_revenue_monthly_last_three_month
   - sum_rev_arpu_total_gprs_net_revenue_monthly_last_month
   - sum_rev_arpu_total_sms_net_revenue_monthly_last_month
   - sum_usg_incoming_total_call_duration_daily_last_ninety_day
   - sum_usg_incoming_total_call_duration_daily_last_seven_day
   - sum_usg_outgoing_data_volume_daily_last_fourteen_day
   - sum_usg_outgoing_data_volume_daily_last_ninety_day
   - sum_usg_outgoing_data_volume_daily_last_seven_day
   - sum_usg_outgoing_total_call_duration_daily_last_ninety_day
   - sum_usg_outgoing_total_call_duration_daily_last_seven_day
   - sum_usg_outgoing_total_sms_daily_last_ninety_day
   - sum_usg_outgoing_total_sms_daily_last_seven_day
   - sum_usg_incoming_data_volume_sum_weekly_last_week
   - sum_usg_incoming_data_volume_sum_weekly_last_twelve_week
   - sum_usg_incoming_data_volume_2G_3G_sum_weekly_last_four_week
   - sum_usg_incoming_data_volume_4G_sum_weekly_last_four_week
   - sum_usg_incoming_local_data_volume_sum_weekly_last_four_week
   - sum_usg_incoming_local_data_volume_2G_3G_sum_weekly_last_four_week
   - sum_usg_incoming_local_data_volume_4G_sum_weekly_last_four_week
   - sum_usg_outgoing_total_call_duration_sum_weekly_last_week
   - sum_usg_outgoing_total_call_duration_sum_weekly_last_twelve_week

## Backtesting parameters
backtesting_model_groups_to_score:
  - "campaign_child_code=1-76784686504"
  - "campaign_child_code=1-47725105277"
  - "campaign_child_code=1-84074046175"
backtesting_models_to_score:
  z_20200508_015902_acceptance_30d_Miguel_: "prediction_acceptance"
  z_20200508_015902_arpu_30d_Miguel_: "prediction_arpu_30d"
  z_20200508_023932_arpu_7d_Miguel_: "prediction_arpu_7d"

backtesting_scoring_chunk_size: 500000

