# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from pipeline.py and the example nodes in
# `src/pipelines/`

l3_streaming_fav_content_group_by_volume_tbl: "l3_streaming_fav_content_group_by_volume"
l3_streaming_fav_content_group_by_duration_tbl: "l3_streaming_fav_content_group_by_duration"
l3_streaming_fav_tv_channel_by_volume_tbl: "l3_streaming_fav_tv_channel_by_volume"
l3_streaming_fav_tv_channel_by_duration_tbl: "l3_streaming_fav_tv_channel_by_duration"
l3_streaming_fav_tv_show_by_episode_watched_tbl: "l3_streaming_fav_tv_show_by_episode_watched"
l3_streaming_fav_video_service_by_download_feature_tbl: "l3_streaming_fav_video_service_by_download_feature"
l3_streaming_2nd_fav_video_service_by_download_feature_tbl: "l3_streaming_2nd_fav_video_service_by_download_feature"
l3_streaming_fav_video_service_by_visit_count_feature_tbl: "l3_streaming_fav_video_service_by_visit_count_feature"
l3_streaming_fav_music_service_by_download_feature_tbl: "l3_streaming_fav_music_service_by_download_feature"
l3_streaming_2nd_fav_music_service_by_download_feature_tbl: "l3_streaming_2nd_fav_music_service_by_download_feature"
l3_streaming_fav_music_service_by_visit_count_feature_tbl: "l3_streaming_fav_music_service_by_visit_count_feature"
l3_streaming_fav_esport_service_by_download_feature_tbl: "l3_streaming_fav_esport_service_by_download_feature"
l3_streaming_2nd_fav_esport_service_by_download_feature_tbl: "l3_streaming_2nd_fav_esport_service_by_download_feature"
l3_streaming_fav_esport_service_by_visit_count_feature_tbl: "l3_streaming_fav_esport_service_by_visit_count_feature"
l3_streaming_visit_count_and_download_traffic_feature_tbl: "l3_streaming_visit_count_and_download_traffic_feature"
l3_streaming_fav_youtube_video_streaming_day_of_week_feature_tbl: "l3_streaming_fav_youtube_video_streaming_day_of_week_feature"
l3_streaming_session_duration_feature_tbl: "l3_streaming_session_duration_feature"
