
# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from pipeline.py and the example nodes in
# `src/pipelines/`

l3_complaints_call_to_competitor_features_tbl: "l3_complaints_call_to_competitor_features"
l3_complaints_nps_after_call_tbl: "l3_complaints_nps_after_call"
l3_complaints_nps_after_chatbot_tbl: "l3_complaints_nps_after_chatbot"
l3_complaints_nps_after_store_visit_tbl: "l3_complaints_nps_after_store_visit"
l3_complaints_traffic_to_dtac_web_resources_tbl: "l3_complaints_traffic_to_dtac_web_resources"
l3_complaints_survey_after_call_tbl: "l3_complaints_survey_after_call"
l3_complaints_survey_after_store_visit_tbl: "l3_complaints_survey_after_store_visit"
l3_complaints_survey_after_chatbot_tbl: "l3_complaints_survey_after_chatbot"

exception_partition_list_for_monthly_l1_complaints_call_to_competitor_features: ["2019-12-01"]
exception_partition_list_for_monthly_l1_complaints_nps_after_call: ["2019-08-01"]
#exception_partition_list_for_monthly_l1_complaints_nps_after_chatbot: ["2019-08-01"]
exception_partition_list_for_monthly_l1_complaints_nps_after_store_visit: ["2019-08-01"]
exception_partition_list_for_monthly_l3_complaints_traffic_to_dtac_web_resources: ["2020-03-01", "2020-04-01", "2021-02-12", "2021-02-23", "2021-05-06", "2021-05-07", "2021-05-08", "2021-05-09", "2021-05-10"]
exception_partition_list_for_monthly_l3_complaints_survey_after_call: ["2020-01-01"]
exception_partition_list_for_monthly_l3_complaints_survey_after_store_visit: ["2020-01-01" ,"2020-10-29"]
exception_partition_list_for_monthly_l3_complaints_survey_after_chatbot: []