
# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from pipeline.py and the example nodes in
# `src/pipelines/`
l4_usage_postpaid_prepaid_weekly_features_min_tg: "l4_usage_postpaid_prepaid_weekly_features_min"
l4_usage_postpaid_prepaid_weekly_features_max_tg: "l4_usage_postpaid_prepaid_weekly_features_max"
l4_usage_postpaid_prepaid_weekly_features_sum_tg: "l4_usage_postpaid_prepaid_weekly_features_sum"
l4_usage_postpaid_prepaid_weekly_features_avg_tg: "l4_usage_postpaid_prepaid_weekly_features_avg"
l4_usage_prepaid_postpaid_daily_features_tg: "l4_usage_prepaid_postpaid_daily_features"