l4_usage_postpaid_prepaid_weekly_features_min: "l4_usage_postpaid_prepaid_weekly_features_min"
l4_usage_postpaid_prepaid_weekly_features_max: "l4_usage_postpaid_prepaid_weekly_features_max"
l4_usage_postpaid_prepaid_weekly_features_avg: "l4_usage_postpaid_prepaid_weekly_features_avg"
l4_usage_postpaid_prepaid_weekly_features_sum: "l4_usage_postpaid_prepaid_weekly_features_sum"