music_mlflow_model_version_prediction: 8
music_mlflow_model_version_training: 8

music_model_group_column: music_campaign_type

music_acceptance_model_target_column: target_response
music_arpu_30d_model_target_column: target_relative_arpu_increase_30d

music_pai_artifacts_uri: "/dbfs/mnt/customer360-blob-data/MUSIC/dev/"
music_pai_runs_uri: "dbfs:/mnt/customer360-blob-data/MUSIC/dev/"

music_model_min_obs_per_class_for_model: 500
music_model_max_rows_per_group: 1000000
music_model_train_sampling_ratio: 0.8
music_scoring_chunk_size: 300000

music_model_model_params:
   n_jobs: 1
   num_leaves: 16
   learning_rate: 0.02
   n_estimators: 200
   min_gain_to_split: 0.0
   random_state: 123456
   importance_type: "gain"

music_acceptance_model_tag: binary

music_extra_tag_columns_pai:
  - campaign_child_code

music_model_input_features:
  l0_music_customer_profile:
    - subscription_status
    - age
    - gender
    - mobile_segment
    - network_type
    - acquisition_channel
    - subscriber_tenure
    - activation_region
    - current_package_name
    - current_package_id
    - cust_active_this_month
    - norms_net_revenue
    - charge_type_numeric
    - network_type_numeric
    - mobile_segment_numeric
    - subscription_status_numeric
    - cust_active_this_month_numeric
  l4_billing_rolling_window_topup_and_volume:
    - sum_payments_top_ups_last_week
    - sum_payments_top_ups_last_four_week
    - sum_payments_top_ups_last_twelve_week
  l4_billing_rolling_window_rpu:
    - sum_payments_arpu_last_month
    - sum_payments_arpu_last_three_month
    - sum_payments_arpu_gprs_last_month
    - sum_payments_arpu_gprs_last_three_month
    - sum_payments_arpu_vas_last_month
    - sum_payments_arpu_vas_last_three_month
    - sum_payments_arpu_voice_last_month
    - sum_payments_arpu_voice_last_three_month
    - payments_one_month_over_three_month_dynamics_arpu
  l4_billing_rolling_window_rpu_roaming:
    - sum_payments_arpu_roaming_weekly_last_week
    - sum_payments_arpu_roaming_weekly_last_twelve_week
  l4_billing_rolling_window_before_top_up_balance:
    - sum_payments_before_top_up_balance_weekly_last_week
    - sum_payments_before_top_up_balance_weekly_last_four_week
  l4_billing_rolling_window_top_up_channels:
    - sum_payments_top_ups_by_bank_atm_cdm_weekly_last_twelve_week
    - sum_payments_top_up_vol_by_bank_atm_cdm_weekly_last_twelve_week
    - sum_payments_top_ups_by_cash_card_weekly_last_twelve_week
    - sum_payments_top_up_vol_by_cash_card_weekly_last_twelve_week
    - sum_payments_top_ups_by_digital_online_self_service_weekly_last_twelve_week
    - sum_payments_top_up_vol_by_digital_online_self_service_weekly_last_twelve_week
    - sum_payments_top_ups_by_epin_slip_weekly_last_twelve_week
    - sum_payments_top_up_vol_by_epin_slip_weekly_last_twelve_week
    - sum_payments_top_ups_by_epos_weekly_last_twelve_week
    - sum_payments_top_up_vol_by_epos_weekly_last_twelve_week
    - sum_payments_top_ups_by_rom_weekly_last_twelve_week
    - sum_payments_top_up_vol_by_rom_weekly_last_twelve_week
  l4_daily_feature_topup_and_volume:
    - sum_payments_top_ups_daily_last_seven_day
    - sum_payments_top_ups_daily_last_thirty_day
    - sum_payments_top_ups_daily_last_ninety_day
  l4_device_summary_features:
    - sum_device_most_used_handset_apple_weekly_last_week
    - sum_device_most_used_handset_oppo_weekly_last_week
    - sum_device_most_used_handset_samsung_weekly_last_week
    - max_device_high_range_weekly_last_week
    - max_device_mid_range_weekly_last_week
    - max_device_low_range_weekly_last_week
    - max_device_smartphone_weekly_last_week
    - max_device_standardphone_weekly_last_week
    - max_device_legacyphone_weekly_last_week
  l4_revenue_prepaid_ru_f_sum_revenue_by_service_monthly:
    - sum_rev_arpu_total_revenue_monthly_last_month
    - sum_rev_arpu_total_revenue_monthly_last_three_month
    - sum_rev_arpu_total_gprs_net_revenue_monthly_last_month
    - sum_rev_arpu_total_sms_net_revenue_monthly_last_month
    - sum_rev_arpu_total_others_net_revenue_monthly_last_month
    - sum_rev_arpu_total_voice_net_revenue_monthly_last_month
    - sum_rev_arpu_total_mms_net_revenue_monthly_last_month
    - sum_rev_arpu_total_ir_net_revenue_monthly_last_month
    - sum_rev_arpu_total_idd_net_revenue_monthly_last_month
    - sum_rev_arpu_total_voice_net_tariff_rev_mth_monthly_last_month
    - sum_rev_arpu_total_gprs_net_tariff_rev_mth_monthly_last_month
    - sum_rev_arpu_total_sms_net_tariff_rev_mth_monthly_last_month
    - sum_rev_arpu_total_mms_net_tariff_rev_mth_monthly_last_month
    - sum_rev_arpu_total_others_net_tariff_rev_mth_monthly_last_month
    - sum_rev_arpu_total_voice_net_tariff_rev_ppu_monthly_last_month
    - sum_rev_arpu_total_gprs_net_tariff_rev_ppu_monthly_last_month
    - sum_rev_arpu_total_sms_net_tariff_rev_ppu_monthly_last_month
    - sum_rev_arpu_total_mms_net_tariff_rev_ppu_monthly_last_month
    - sum_rev_arpu_total_others_net_tariff_rev_ppu_monthly_last_month
    - sum_rev_arpu_total_ir_net_tariff_rev_ppu_monthly_last_month
    - sum_rev_arpu_total_idd_net_tariff_rev_ppu_monthly_last_month
  l4_streaming_visit_count_and_download_traffic_feature_full_load_data_blob:
    - sum_download_kb_traffic_youtube_video_sum_weekly_last_four_week
    - sum_download_kb_traffic_facebook_video_sum_weekly_last_four_week
    - sum_download_kb_traffic_linetv_video_sum_weekly_last_four_week
    - sum_download_kb_traffic_ais_play_video_sum_weekly_last_four_week
    - sum_download_kb_traffic_netflix_video_sum_weekly_last_four_week
    - sum_download_kb_traffic_spotify_music_sum_weekly_last_four_week
    - sum_download_kb_traffic_twitch_esport_sum_weekly_last_four_week
    - sum_download_kb_traffic_mixer_esport_sum_weekly_last_four_week
  l4_usage_prepaid_postpaid_daily_features:
    - sum_usg_incoming_total_call_duration_daily_last_ninety_day
    - sum_usg_incoming_total_call_duration_daily_last_seven_day
    - sum_usg_outgoing_data_volume_daily_last_fourteen_day
    - sum_usg_outgoing_data_volume_daily_last_ninety_day
    - sum_usg_outgoing_data_volume_daily_last_seven_day
    - sum_usg_outgoing_total_call_duration_daily_last_ninety_day
    - sum_usg_outgoing_total_call_duration_daily_last_seven_day
    - sum_usg_outgoing_total_sms_daily_last_ninety_day
    - sum_usg_outgoing_total_sms_daily_last_seven_day
  l4_usage_postpaid_prepaid_weekly_features_sum:
    - sum_usg_incoming_data_volume_sum_weekly_last_week
    - sum_usg_incoming_data_volume_sum_weekly_last_four_week
    - sum_usg_incoming_data_volume_sum_weekly_last_twelve_week
    - sum_usg_incoming_data_volume_2G_3G_sum_weekly_last_four_week
    - sum_usg_incoming_data_volume_4G_sum_weekly_last_four_week
    - sum_usg_incoming_local_data_volume_sum_weekly_last_four_week
    - sum_usg_incoming_local_data_volume_2G_3G_sum_weekly_last_four_week
    - sum_usg_incoming_local_data_volume_4G_sum_weekly_last_four_week
    - sum_usg_incoming_roaming_data_volume_sum_weekly_last_twelve_week
    - sum_usg_outgoing_data_volume_sum_weekly_last_four_week
    - sum_usg_total_data_volume_sum_weekly_last_week
    - sum_usg_total_data_volume_sum_weekly_last_four_week
    - sum_usg_total_data_volume_sum_weekly_last_twelve_week
    - sum_usg_incoming_roaming_call_duration_sum_weekly_last_week
    - sum_usg_incoming_roaming_call_duration_sum_weekly_last_twelve_week
    - sum_usg_incoming_local_call_duration_sum_weekly_last_week
    - sum_usg_incoming_local_call_duration_sum_weekly_last_four_week
    - sum_usg_incoming_local_call_duration_sum_weekly_last_twelve_week
    - sum_usg_incoming_total_sms_sum_weekly_last_week
    - sum_usg_incoming_total_sms_sum_weekly_last_twelve_week
    - sum_usg_incoming_weekday_calls_duration_sum_weekly_last_four_week
    - sum_usg_incoming_weekday_number_calls_sum_weekly_last_four_week
    - sum_usg_incoming_weekend_calls_duration_sum_weekly_last_four_week
    - sum_usg_incoming_weekend_number_calls_sum_weekly_last_four_week
    - sum_usg_outgoing_total_call_duration_sum_weekly_last_week
    - sum_usg_outgoing_total_call_duration_sum_weekly_last_four_week
    - sum_usg_outgoing_total_call_duration_sum_weekly_last_twelve_week
    - sum_usg_outgoing_total_sms_sum_weekly_last_week
    - sum_usg_outgoing_total_sms_sum_weekly_last_four_week
    - sum_usg_outgoing_total_sms_sum_weekly_last_twelve_week
  l4_touchpoints_to_call_center_features:
    - sum_touchpoints_number_of_calls_on_cc_sum_weekly_last_week
    - sum_touchpoints_number_of_calls_on_cc_sum_weekly_last_two_week
    - sum_touchpoints_number_of_calls_on_cc_sum_weekly_last_four_week
    - sum_touchpoints_number_of_calls_on_cc_sum_weekly_last_twelve_week
  l2_device_summary_with_config_weekly_full_load:
    - device_supports_dual_sim
    - devices_uses_both_sim_slot
  l4_revenue_postpaid_ru_f_sum_revenue_by_service_monthly:
    - sum_rev_arpu_total_revenue_monthly_last_three_month
    - sum_rev_arpu_total_gprs_net_revenue_monthly_last_three_month
    - sum_rev_arpu_total_vas_net_revenue_monthly_last_three_month
    - sum_rev_arpu_total_sms_net_revenue_monthly_last_three_month
    - sum_rev_arpu_total_others_net_revenue_monthly_last_three_month
    - sum_rev_arpu_total_voice_net_revenue_monthly_last_three_month
    - sum_rev_arpu_total_mms_net_revenue_monthly_last_three_month
    - sum_rev_arpu_total_ir_net_revenue_monthly_last_three_month
    - sum_rev_arpu_total_idd_net_revenue_monthly_last_three_month
  l4_streaming_fav_youtube_video_streaming_day_of_week_feature:
    - fav_youtube_video_streaming_day_of_week_last_four_week
    - fav_youtube_video_streaming_day_of_week_last_twelve_week
  l4_streaming_fav_joox_music_streaming_day_of_week_feature:
    - fav_joox_music_streaming_day_of_week_last_week
    - fav_joox_music_streaming_day_of_week_last_four_week
    - fav_joox_music_streaming_day_of_week_last_twelve_week
  l4_streaming_fav_spotify_music_streaming_day_of_week_feature:
    - fav_spotify_music_streaming_day_of_week_last_week
    - fav_spotify_music_streaming_day_of_week_last_four_week
    - fav_spotify_music_streaming_day_of_week_last_twelve_week
  l4_campaign_postpaid_prepaid_features:
    - avg_campaign_total_others_by_sms_sum_weekly_last_twelve_week
    - sum_campaign_total_by_sms_sum_weekly_last_four_week_over_twelve_weeks
    - sum_campaign_total_others_by_sms_sum_weekly_last_four_week_over_twelve_weeks
    - avg_campaign_overall_count_sum_weekly_last_twelve_week
    - avg_campaign_total_others_by_ussd_sum_weekly_last_twelve_week
    - avg_campaign_total_eligible_by_sms_sum_weekly_last_twelve_week
    - sum_campaign_total_eligible_by_sms_sum_weekly_last_four_week_over_twelve_weeks
    - avg_campaign_overall_count_sum_weekly_last_four_week
    - avg_campaign_total_others_by_myais_app_sum_weekly_last_twelve_week
    - sum_campaign_total_upsell_xsell_by_sms_sum_weekly_last_four_week_over_twelve_weeks
    - sum_campaign_total_others_eligible_by_sms_sum_weekly_four_week_over_twelve_weeks
    - avg_campaign_total_upsell_xsell_by_sms_sum_weekly_last_twelve_week
    - avg_campaign_overall_count_sum_weekly_last_two_week
    - max_campaign_overall_count_sum_weekly_last_twelve_week

music_model_explanatory_features:
 - sum_usg_outgoing_total_call_duration_daily_last_seven_day
 - sum_payments_before_top_up_balance_weekly_last_four_week
 - sum_payments_before_top_up_balance_weekly_last_week
 - sum_usg_outgoing_total_call_duration_sum_weekly_last_week
 - subscriber_tenure
 - sum_payments_top_up_vol_by_digital_online_self_service_weekly_last_twelve_week
 - norms_net_revenue
 - sum_usg_outgoing_data_volume_daily_last_ninety_day
 - sum_usg_outgoing_data_volume_daily_last_seven_day
 - sum_usg_incoming_total_call_duration_daily_last_ninety_day
 - sum_usg_outgoing_data_volume_daily_last_fourteen_day
 - sum_usg_incoming_total_call_duration_daily_last_seven_day
 - sum_usg_incoming_data_volume_sum_weekly_last_week
 - sum_usg_incoming_data_volume_2G_3G_sum_weekly_last_four_week
 - sum_usg_incoming_data_volume_sum_weekly_last_twelve_week
 - avg_campaign_total_others_by_sms_sum_weekly_last_twelve_week
 - sum_campaign_total_by_sms_sum_weekly_last_four_week_over_twelve_weeks
 - sum_payments_arpu_voice_last_month
 - sum_payments_arpu_voice_last_three_month
 - sum_rev_arpu_total_gprs_net_revenue_monthly_last_month
 - sum_campaign_total_others_by_sms_sum_weekly_last_four_week_over_twelve_weeks
 - day_of_month
 - sum_usg_outgoing_total_call_duration_sum_weekly_last_twelve_week
 - age
 - sum_payments_arpu_gprs_last_three_month
 - sum_usg_incoming_local_data_volume_sum_weekly_last_four_week
 - sum_usg_outgoing_total_call_duration_daily_last_ninety_day
 - avg_campaign_overall_count_sum_weekly_last_twelve_week
 - avg_campaign_total_others_by_ussd_sum_weekly_last_twelve_week
 - avg_campaign_total_eligible_by_sms_sum_weekly_last_twelve_week
 - sum_rev_arpu_total_revenue_monthly_last_month
 - sum_campaign_total_eligible_by_sms_sum_weekly_last_four_week_over_twelve_weeks
 - sum_usg_incoming_data_volume_4G_sum_weekly_last_four_week
 - avg_campaign_overall_count_sum_weekly_last_four_week
 - sum_payments_arpu_gprs_last_month
 - sum_payments_arpu_last_month
 - sum_payments_arpu_vas_last_three_month
 - sum_payments_arpu_last_three_month
 - sum_payments_arpu_vas_last_month
 - sum_payments_top_up_vol_by_rom_weekly_last_twelve_week
 - day_of_week
 - avg_campaign_total_others_by_myais_app_sum_weekly_last_twelve_week
 - sum_payments_top_ups_by_rom_weekly_last_twelve_week
 - sum_campaign_total_upsell_xsell_by_sms_sum_weekly_last_four_week_over_twelve_weeks
 - sum_campaign_total_others_eligible_by_sms_sum_weekly_four_week_over_twelve_weeks
 - sum_usg_outgoing_total_sms_daily_last_ninety_day
 - max_device_high_range_weekly_last_week
 - avg_campaign_total_upsell_xsell_by_sms_sum_weekly_last_twelve_week
 - mobile_segment_numeric
 - max_device_low_range_weekly_last_week
 - sum_rev_arpu_total_sms_net_revenue_monthly_last_month
 - sum_usg_outgoing_total_sms_daily_last_seven_day
 - sum_usg_incoming_local_data_volume_4G_sum_weekly_last_four_week
 - sum_usg_incoming_local_data_volume_2G_3G_sum_weekly_last_four_week
 - subscription_status_numeric
 - charge_type_numeric

