exception_partition_list_for_l1_loyalty_number_of_services_daily: ['2020-01-27','2020-02-23']
exception_partition_list_for_l1_loyalty_number_of_rewards_daily: ['2020-01-27','2020-02-23']
exception_partition_list_for_l1_loyalty_number_of_points_spend_daily: ['2020-01-27','2020-02-23']
