exception_partition_list_for_l0_product_fbb_a_customer_promotion_current_for_daily: ['2020-12-27']

exception_partition_l1_product_active_customer_promotion_features_prepaid_postpaid: ["2021-02-19","2021-02-20","2021-02-21","2021-02-22","2021-02-23"]
exception_partition_l1_product_active_customer_promotion_features_daily: ["2021-02-19","2021-02-20","2021-02-21","2021-02-22","2021-02-23"]