# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from pipeline.py and the example nodes in
# `src/pipelines/`

streaming_app:
  - "youtube_video"
  - "facebook_video"
  - "linetv_video"
  - "ais_play_video"
  - "netflix_video"
  - "hooq_video"
  - "iflix_video"
  - "spotify_music"
  - "joox_music"
  - "twitch_esport"
  - "bigo_esport"
  - "mixer_esport"
  - "steamtv_esport"
